import { SQL_MAP } from "@/constants/sql-map";
import type { LookupConfig } from "@/features/client/types/lookup";

export const BRAND_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_BRAND_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_BRAND_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_BRAND_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_ALL_BRANDS,
    tableName:                     "brand",
    codeLettersOnly:               true,   // DB CHECK: ^[A-Z_]+$
    hasDescription:                false,
    hasDisplayOrder:               false,
    hasIsActive:                   true,
    hasPrefix:                     false,
    hasSystemFlag:                 false,  // brand has no is_system column
    sectionTitle:                  "Brands",
    sectionDescription:            "Manage product brands.",
    messages: {
        createFailed: "Failed to create brand. Please try again.",
        created:      "Brand created successfully.",
        deleteFailed: "Failed to delete brand. Please try again.",
        deleted:      "Brand deleted successfully.",
        deleteInUse:  "This brand cannot be deleted as it is used by models or spare parts.",
        loadFailed:   "Failed to load brands. Please try again.",
        updateFailed: "Failed to update brand. Please try again.",
        updated:      "Brand updated successfully.",
    },
};

export const CUSTOMER_TYPE_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_CUSTOMER_TYPE_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_CUSTOMER_TYPE_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_CUSTOMER_TYPE_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_CUSTOMER_TYPES,
    tableName:                     "customer_type",
    codeLettersOnly:               false,
    hasDescription:                true,
    hasDisplayOrder:               true,
    hasIsActive:                   true,
    hasPrefix:                     false,
    sectionTitle:                  "Customer Types",
    sectionDescription:            "Manage customer type classifications.",
    messages: {
        createFailed: "Failed to create customer type. Please try again.",
        created:      "Customer type created successfully.",
        deleteFailed: "Failed to delete customer type. Please try again.",
        deleted:      "Customer type deleted successfully.",
        deleteInUse:  "This customer type cannot be deleted as it is assigned to existing customers.",
        loadFailed:   "Failed to load customer types. Please try again.",
        updateFailed: "Failed to update customer type. Please try again.",
        updated:      "Customer type updated successfully.",
    },
};

export const DOCUMENT_TYPE_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_DOCUMENT_TYPE_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_DOCUMENT_TYPE_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_DOCUMENT_TYPE_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_DOCUMENT_TYPES,
    tableName:                     "document_type",
    codeLettersOnly:               true,  // DB CHECK: ^[A-Z_]+$
    hasDescription:                true,
    hasDisplayOrder:               false,
    hasIsActive:                   false,
    hasPrefix:                     true,
    sectionTitle:                  "Document Types",
    sectionDescription:            "Manage document type definitions (e.g. Job card, Invoice).",
    messages: {
        createFailed: "Failed to create document type. Please try again.",
        created:      "Document type created successfully.",
        deleteFailed: "Failed to delete document type. Please try again.",
        deleted:      "Document type deleted successfully.",
        deleteInUse:  "This document type cannot be deleted as it is used in document sequences.",
        loadFailed:   "Failed to load document types. Please try again.",
        updateFailed: "Failed to update document type. Please try again.",
        updated:      "Document type updated successfully.",
    },
};

export const JOB_TYPE_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_JOB_TYPE_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_JOB_TYPE_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_JOB_TYPE_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_JOB_TYPES,
    tableName:                     "job_type",
    codeLettersOnly:               false,
    hasDescription:                true,
    hasDisplayOrder:               true,
    hasIsActive:                   true,
    hasPrefix:                     false,
    sectionTitle:                  "Job Types",
    sectionDescription:            "Manage job type classifications.",
    messages: {
        createFailed: "Failed to create job type. Please try again.",
        created:      "Job type created successfully.",
        deleteFailed: "Failed to delete job type. Please try again.",
        deleted:      "Job type deleted successfully.",
        deleteInUse:  "This job type cannot be deleted as it is assigned to existing jobs.",
        loadFailed:   "Failed to load job types. Please try again.",
        updateFailed: "Failed to update job type. Please try again.",
        updated:      "Job type updated successfully.",
    },
};

export const JOB_RECEIVE_MANNER_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_JOB_RECEIVE_MANNER_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_JOB_RECEIVE_MANNER_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_JOB_RECEIVE_MANNER_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_JOB_RECEIVE_MANNERS,
    tableName:                     "job_receive_manner",
    codeLettersOnly:               false,
    hasDescription:                false,
    hasDisplayOrder:               true,
    hasIsActive:                   true,
    hasPrefix:                     false,
    sectionTitle:                  "Job Receive Manners",
    sectionDescription:            "Manage how jobs are received (e.g. Walk-in, Courier).",
    messages: {
        createFailed: "Failed to create job receive manner. Please try again.",
        created:      "Job receive manner created successfully.",
        deleteFailed: "Failed to delete job receive manner. Please try again.",
        deleted:      "Job receive manner deleted successfully.",
        deleteInUse:  "This job receive manner cannot be deleted as it is assigned to existing jobs.",
        loadFailed:   "Failed to load job receive manners. Please try again.",
        updateFailed: "Failed to update job receive manner. Please try again.",
        updated:      "Job receive manner updated successfully.",
    },
};

export const JOB_DELIVERY_MANNER_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_JOB_DELIVERY_MANNER_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_JOB_DELIVERY_MANNER_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_JOB_DELIVERY_MANNER_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_JOB_DELIVERY_MANNERS,
    tableName:                     "job_delivery_manner",
    codeLettersOnly:               false,
    hasDescription:                false,
    hasDisplayOrder:               true,
    hasIsActive:                   true,
    hasPrefix:                     false,
    sectionTitle:                  "Job Delivery Manners",
    sectionDescription:            "Manage how completed jobs are delivered back to customers.",
    messages: {
        createFailed: "Failed to create job delivery manner. Please try again.",
        created:      "Job delivery manner created successfully.",
        deleteFailed: "Failed to delete job delivery manner. Please try again.",
        deleted:      "Job delivery manner deleted successfully.",
        deleteInUse:  "This job delivery manner cannot be deleted as it is referenced by existing records.",
        loadFailed:   "Failed to load job delivery manners. Please try again.",
        updateFailed: "Failed to update job delivery manner. Please try again.",
        updated:      "Job delivery manner updated successfully.",
    },
};

export const JOB_RECEIVE_CONDITION_CONFIG: LookupConfig = {
    checkCodeExistsSqlId:          SQL_MAP.CHECK_JOB_RECEIVE_CONDITION_CODE_EXISTS,
    checkCodeExistsExcludeIdSqlId: SQL_MAP.CHECK_JOB_RECEIVE_CONDITION_CODE_EXISTS_EXCLUDE_ID,
    checkInUseSqlId:               SQL_MAP.CHECK_JOB_RECEIVE_CONDITION_IN_USE,
    getAllSqlId:                   SQL_MAP.GET_JOB_RECEIVE_CONDITIONS,
    tableName:                     "job_receive_condition",
    codeLettersOnly:               false,
    hasDescription:                true,
    hasDisplayOrder:               true,
    hasIsActive:                   true,
    hasPrefix:                     false,
    sectionTitle:                  "Job Receive Conditions",
    sectionDescription:            "Manage the condition in which jobs are received (e.g. Good, Damaged).",
    messages: {
        createFailed: "Failed to create job receive condition. Please try again.",
        created:      "Job receive condition created successfully.",
        deleteFailed: "Failed to delete job receive condition. Please try again.",
        deleted:      "Job receive condition deleted successfully.",
        deleteInUse:  "This job receive condition cannot be deleted as it is assigned to existing jobs.",
        loadFailed:   "Failed to load job receive conditions. Please try again.",
        updateFailed: "Failed to update job receive condition. Please try again.",
        updated:      "Job receive condition updated successfully.",
    },
};
