# AUTO-GENERATED by app/db/tools/extract_schema.py from service_plus_service.sql
# Do not hand-edit; re-run the extractor instead.

class SqlBu:
    """DDL generated from service_plus_service.sql. Do not hand-edit."""

    BU_SCHEMA_DDL = """
        CREATE FUNCTION fn_maintain_stock_balance() RETURNS trigger
            LANGUAGE plpgsql
            AS $$
        DECLARE
            v_effect NUMERIC(12,3);
        BEGIN

            IF TG_OP = 'INSERT' THEN

                v_effect := CASE NEW.dr_cr WHEN 'D' THEN NEW.qty ELSE -NEW.qty END;

                INSERT INTO stock_balance (part_id, branch_id, qty)
                VALUES (NEW.part_id, NEW.branch_id, v_effect)
                ON CONFLICT (part_id, branch_id)
                DO UPDATE SET
                    qty        = stock_balance.qty + EXCLUDED.qty,
                    updated_at = now();

            ELSIF TG_OP = 'DELETE' THEN

                -- Reverse the old row's effect
                v_effect := CASE OLD.dr_cr WHEN 'D' THEN -OLD.qty ELSE OLD.qty END;

                INSERT INTO stock_balance (part_id, branch_id, qty)
                VALUES (OLD.part_id, OLD.branch_id, v_effect)
                ON CONFLICT (part_id, branch_id)
                DO UPDATE SET
                    qty        = stock_balance.qty + EXCLUDED.qty,
                    updated_at = now();

            ELSIF TG_OP = 'UPDATE' THEN

                -- Step 1: reverse the old row's effect (handles part_id/branch_id changes too)
                v_effect := CASE OLD.dr_cr WHEN 'D' THEN -OLD.qty ELSE OLD.qty END;

                INSERT INTO stock_balance (part_id, branch_id, qty)
                VALUES (OLD.part_id, OLD.branch_id, v_effect)
                ON CONFLICT (part_id, branch_id)
                DO UPDATE SET
                    qty        = stock_balance.qty + EXCLUDED.qty,
                    updated_at = now();

                -- Step 2: apply the new row's effect
                v_effect := CASE NEW.dr_cr WHEN 'D' THEN NEW.qty ELSE -NEW.qty END;

                INSERT INTO stock_balance (part_id, branch_id, qty)
                VALUES (NEW.part_id, NEW.branch_id, v_effect)
                ON CONFLICT (part_id, branch_id)
                DO UPDATE SET
                    qty        = stock_balance.qty + EXCLUDED.qty,
                    updated_at = now();

            END IF;

            RETURN NULL;
        END;
        $$;

        SET default_tablespace = '';

        SET default_table_access_method = heap;

        CREATE TABLE additional_charge (
            id smallint NOT NULL,
            name text NOT NULL,
            hsn_code text
        );

        CREATE TABLE app_setting (
            id smallint NOT NULL,
            setting_key text NOT NULL,
            setting_value jsonb NOT NULL,
            description text,
            is_editable boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        CREATE TABLE branch (
            id bigint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            phone text,
            email text,
            address_line1 text NOT NULL,
            address_line2 text,
            state_id integer NOT NULL,
            city text,
            pincode text NOT NULL,
            gstin text,
            is_active boolean DEFAULT true NOT NULL,
            is_head_office boolean DEFAULT false NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT branch_code_check CHECK ((code ~ '^[A-Z0-9_]+$'::text)),
            CONSTRAINT branch_gstin_check CHECK (((gstin IS NULL) OR (gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'::text)))
        );

        ALTER TABLE branch ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME branch_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE brand (
            id bigint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT brand_code_check CHECK ((code ~ '^[A-Z_]+$'::text))
        );

        ALTER TABLE brand ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME brand_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE customer_contact (
            id bigint NOT NULL,
            customer_type_id smallint NOT NULL,
            full_name text NOT NULL,
            gstin text,
            mobile text NOT NULL,
            alternate_mobile text,
            email text,
            address_line1 text NOT NULL,
            address_line2 text,
            landmark text,
            state_id integer NOT NULL,
            city text,
            postal_code text,
            remarks text,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        ALTER TABLE customer_contact ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME customer_contact_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE customer_type (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            description text,
            is_active boolean DEFAULT true NOT NULL,
            display_order smallint,
            is_system boolean NOT NULL
        );

        CREATE TABLE division (
            id bigint NOT NULL,
            name text NOT NULL,
            address_line1 text NOT NULL,
            address_line2 text,
            city text,
            state_id integer NOT NULL,
            country text DEFAULT 'IN'::text,
            pincode text,
            phone text,
            email text,
            gstin text,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            branch_id bigint NOT NULL,
            code text NOT NULL,
            web_site text,
            account_setting jsonb
        );

        CREATE TABLE document_sequence (
            id bigint NOT NULL,
            document_type_id smallint NOT NULL,
            branch_id bigint NOT NULL,
            prefix text,
            next_number bigint NOT NULL,
            padding smallint DEFAULT 0 NOT NULL,
            separator text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            division_id bigint
        );

        ALTER TABLE document_sequence ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME document_sequence_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE document_type (
            id smallint NOT NULL,
            code text NOT NULL,
            prefix text,
            name text NOT NULL,
            description text,
            is_system boolean NOT NULL,
            CONSTRAINT document_type_code_chk CHECK ((code ~ '^[A-Z_]+$'::text))
        );

        CREATE TABLE financial_year (
            id integer NOT NULL,
            start_date date NOT NULL,
            end_date date NOT NULL,
            CONSTRAINT financial_year_date_check CHECK ((start_date < end_date))
        );

        CREATE TABLE job (
            id bigint NOT NULL,
            job_no text NOT NULL,
            job_date date DEFAULT CURRENT_DATE NOT NULL,
            customer_contact_id bigint NOT NULL,
            branch_id bigint NOT NULL,
            technician_id bigint,
            job_status_id smallint NOT NULL,
            job_type_id smallint NOT NULL,
            job_receive_manner_id smallint NOT NULL,
            job_receive_condition_id smallint,
            product_brand_model_id bigint NOT NULL,
            serial_no text,
            problem_reported text,
            diagnosis text,
            work_done text,
            remarks text,
            amount numeric(12,2) DEFAULT 0 NOT NULL,
            delivery_date date,
            is_closed boolean DEFAULT false NOT NULL,
            warranty_card_no text,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            address_snapshot text,
            last_transaction_id bigint,
            is_final boolean DEFAULT false NOT NULL,
            qty integer DEFAULT 1 NOT NULL,
            batch_no integer,
            estimate_amount numeric(12,2) DEFAULT 0 NOT NULL,
            alternate_job_no text,
            division_id bigint NOT NULL,
            is_igst boolean DEFAULT false NOT NULL,
            to_show_parts_in_job_invoice boolean DEFAULT true NOT NULL,
            CONSTRAINT job_qty_check CHECK ((qty <> 0))
        );

        CREATE TABLE job_additional_charge (
            id bigint NOT NULL,
            job_id bigint NOT NULL,
            charge_name text NOT NULL,
            ref_no text,
            description text,
            cost_price numeric(12,2) DEFAULT 0 NOT NULL,
            selling_price numeric(12,2) DEFAULT 0 NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            hsn_code text,
            gst_rate numeric(5,2) DEFAULT 0 NOT NULL,
            qty numeric(12,2) DEFAULT 1 NOT NULL,
            CONSTRAINT job_add_charge_cost_check CHECK ((cost_price >= (0)::numeric)),
            CONSTRAINT job_add_charge_sell_check CHECK ((selling_price >= (0)::numeric))
        );

        ALTER TABLE job_additional_charge ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_additional_charge_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE SEQUENCE job_batch_no_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;

        ALTER SEQUENCE job_batch_no_seq OWNED BY job.batch_no;

        CREATE TABLE job_delivery_manner (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            display_order smallint,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            is_system boolean NOT NULL
        );

        ALTER TABLE job ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_image_doc (
            id bigint NOT NULL,
            job_id bigint NOT NULL,
            url text NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            about text NOT NULL
        );

        ALTER TABLE job_image_doc ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_image_doc_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_invoice (
            id bigint NOT NULL,
            job_id bigint NOT NULL,
            invoice_no text NOT NULL,
            invoice_date date DEFAULT CURRENT_DATE NOT NULL,
            supply_state_code character(2) NOT NULL,
            aggregate numeric(14,2) NOT NULL,
            cgst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            sgst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            igst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            amount numeric(14,2) NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            is_posted boolean DEFAULT false NOT NULL
        );

        ALTER TABLE job_invoice ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_invoice_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_invoice_line (
            id bigint NOT NULL,
            job_invoice_id bigint NOT NULL,
            description text NOT NULL,
            part_code text,
            qty numeric(10,2) NOT NULL,
            price numeric(12,2) NOT NULL,
            aggregate numeric(12,2) NOT NULL,
            gst_rate numeric(5,2) DEFAULT 0 NOT NULL,
            cgst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            sgst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            igst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            amount numeric(12,2) NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            hsn_code text,
            CONSTRAINT job_invoice_line_quantity_check CHECK ((qty > (0)::numeric)),
            CONSTRAINT job_invoice_line_unit_price_check CHECK ((price >= (0)::numeric))
        );

        ALTER TABLE job_invoice_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_invoice_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_part_used (
            id bigint NOT NULL,
            job_id bigint NOT NULL,
            part_id bigint NOT NULL,
            qty numeric(10,2) NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            remarks text,
            cost_price numeric(12,2) DEFAULT 0 NOT NULL,
            selling_price numeric(12,2) DEFAULT 0 NOT NULL,
            gst_rate numeric(5,2) DEFAULT 0 NOT NULL,
            hsn_code text,
            CONSTRAINT job_part_used_quantity_check CHECK ((qty > (0)::numeric))
        );

        ALTER TABLE job_part_used ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_part_used_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_payment (
            id bigint NOT NULL,
            job_id bigint NOT NULL,
            payment_date date NOT NULL,
            payment_mode text NOT NULL,
            amount numeric(14,2) NOT NULL,
            reference_no text,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            is_posted boolean DEFAULT false NOT NULL,
            receipt_no text NOT NULL,
            CONSTRAINT job_payment_amount_check CHECK ((amount > (0)::numeric))
        );

        ALTER TABLE job_payment ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_payment_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_receive_condition (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            description text,
            display_order smallint DEFAULT 0 NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            is_system boolean NOT NULL
        );

        CREATE TABLE job_receive_manner (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            is_system boolean DEFAULT true NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            display_order smallint DEFAULT 0 NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        CREATE TABLE job_status (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            description text,
            display_order smallint NOT NULL,
            is_initial boolean DEFAULT false NOT NULL,
            is_final boolean DEFAULT false NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            is_system boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT job_status_code_check CHECK ((code ~ '^[A-Z_]+$'::text))
        );

        CREATE TABLE job_transaction (
            id bigint NOT NULL,
            job_id bigint NOT NULL,
            status_id smallint,
            technician_id bigint,
            amount numeric(12,2),
            performed_by_user_id bigint NOT NULL,
            performed_at timestamp with time zone DEFAULT now() NOT NULL,
            previous_transaction_id bigint,
            remarks text,
            transaction_date date DEFAULT now() NOT NULL
        );

        ALTER TABLE job_transaction ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME job_transaction_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE job_type (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            description text,
            display_order smallint DEFAULT 0 NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            is_system boolean NOT NULL
        );

        CREATE TABLE product (
            id bigint NOT NULL,
            name text NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT product_name_check CHECK ((name ~ '^[A-Z_]+$'::text))
        );

        CREATE TABLE product_brand_model (
            id bigint NOT NULL,
            product_id bigint NOT NULL,
            brand_id bigint NOT NULL,
            model_name text NOT NULL,
            launch_year integer,
            remarks text,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        ALTER TABLE product_brand_model ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME product_brand_model_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        ALTER TABLE product ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME product_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE purchase_invoice (
            id bigint NOT NULL,
            supplier_id bigint NOT NULL,
            invoice_no text NOT NULL,
            invoice_date date NOT NULL,
            aggregate_amount numeric(14,2) NOT NULL,
            cgst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            sgst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            igst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            total_tax numeric(14,2) NOT NULL,
            total_amount numeric(14,2) NOT NULL,
            branch_id bigint NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            brand_id bigint NOT NULL,
            is_return boolean DEFAULT false NOT NULL,
            is_posted boolean DEFAULT false NOT NULL,
            division_id bigint NOT NULL
        );

        ALTER TABLE purchase_invoice ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME purchase_invoice_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE purchase_invoice_line (
            id bigint NOT NULL,
            purchase_invoice_id bigint NOT NULL,
            part_id bigint NOT NULL,
            hsn_code text NOT NULL,
            qty numeric(12,2) NOT NULL,
            unit_price numeric(12,2) NOT NULL,
            aggregate_amount numeric(12,2) NOT NULL,
            gst_rate numeric(5,2) DEFAULT 0 NOT NULL,
            cgst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            sgst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            igst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            total_amount numeric(12,2) NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            under_warranty boolean DEFAULT false NOT NULL,
            remarks text,
            CONSTRAINT purchase_invoice_line_quantity_check CHECK ((qty > (0)::numeric)),
            CONSTRAINT purchase_invoice_line_unit_price_check CHECK ((unit_price >= (0)::numeric))
        );

        ALTER TABLE purchase_invoice_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME purchase_invoice_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE sales_invoice (
            id bigint NOT NULL,
            invoice_no text NOT NULL,
            invoice_date date NOT NULL,
            customer_contact_id bigint NOT NULL,
            customer_name text NOT NULL,
            customer_gstin text,
            customer_state_code character(2) NOT NULL,
            aggregate numeric(14,2) NOT NULL,
            cgst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            sgst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            igst_amount numeric(14,2) DEFAULT 0 NOT NULL,
            amount numeric(14,2) NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            is_return boolean DEFAULT false NOT NULL,
            division_id bigint NOT NULL,
            is_posted boolean DEFAULT false NOT NULL,
            brand_id bigint NOT NULL
        );

        ALTER TABLE sales_invoice ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME sales_invoice_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE sales_invoice_line (
            id bigint NOT NULL,
            sales_invoice_id bigint NOT NULL,
            part_id bigint NOT NULL,
            item_description text NOT NULL,
            hsn_code text NOT NULL,
            qty numeric(12,2) NOT NULL,
            price numeric(12,2) NOT NULL,
            gst_rate numeric(5,2) DEFAULT 0 NOT NULL,
            amount numeric(12,2) NOT NULL,
            cgst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            sgst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            igst_amount numeric(12,2) DEFAULT 0 NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            remarks text,
            cost_price numeric(12,2) DEFAULT 0 NOT NULL,
            CONSTRAINT sales_invoice_line_quantity_check CHECK ((qty > (0)::numeric)),
            CONSTRAINT sales_invoice_line_unit_price_check CHECK ((price >= (0)::numeric))
        );

        ALTER TABLE sales_invoice_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME sales_invoice_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE spare_part_master (
            id bigint NOT NULL,
            brand_id bigint NOT NULL,
            part_code text NOT NULL,
            part_name text NOT NULL,
            part_description text,
            category text,
            model text,
            uom text DEFAULT 'NOS'::text NOT NULL,
            cost_price numeric(12,2),
            mrp numeric(12,2),
            hsn_code text,
            gst_rate numeric(5,2),
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now(),
            updated_at timestamp with time zone DEFAULT now(),
            selling_price numeric(12,2) DEFAULT 0 NOT NULL
        );

        ALTER TABLE spare_part_master ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME spare_part_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_location_change (
            id bigint NOT NULL,
            part_id bigint NOT NULL,
            branch_id bigint NOT NULL,
            to_location_id bigint NOT NULL,
            transaction_date date NOT NULL,
            ref_no text,
            remarks text,
            created_at timestamp with time zone DEFAULT now()
        );

        ALTER TABLE stock_location_change ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME spare_part_location_change_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_location_master (
            id bigint NOT NULL,
            branch_id bigint NOT NULL,
            name text NOT NULL,
            is_active boolean DEFAULT true NOT NULL
        );

        ALTER TABLE stock_location_master ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME spare_part_location_master_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE state (
            id integer NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            country_code text DEFAULT 'IN'::text NOT NULL,
            gst_state_code character(2),
            is_union_territory boolean DEFAULT false NOT NULL,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT country_code_check CHECK ((country_code ~ '^[A-Z]{2}$'::text)),
            CONSTRAINT state_code_check CHECK ((code ~ '^[A-Z]{2}$'::text))
        );

        CREATE TABLE stock_adjustment (
            id bigint NOT NULL,
            adjustment_date date NOT NULL,
            adjustment_reason text NOT NULL,
            ref_no text,
            branch_id bigint NOT NULL,
            remarks text,
            created_by bigint,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        ALTER TABLE stock_adjustment ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_adjustment_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_adjustment_line (
            id bigint NOT NULL,
            stock_adjustment_id bigint NOT NULL,
            part_id bigint NOT NULL,
            dr_cr character(1) NOT NULL,
            qty numeric(12,3) NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT stock_adjustment_line_dr_cr_check CHECK ((dr_cr = ANY (ARRAY['D'::bpchar, 'C'::bpchar]))),
            CONSTRAINT stock_adjustment_line_qty_check CHECK ((qty > (0)::numeric))
        );

        ALTER TABLE stock_adjustment_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_adjustment_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_balance (
            part_id bigint NOT NULL,
            branch_id bigint NOT NULL,
            qty numeric(12,3) DEFAULT 0 NOT NULL,
            location_id bigint,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        CREATE TABLE stock_branch_transfer (
            id bigint NOT NULL,
            transfer_date date NOT NULL,
            from_branch_id bigint NOT NULL,
            to_branch_id bigint NOT NULL,
            ref_no text,
            remarks text,
            created_by bigint,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT stock_branch_transfer_check CHECK ((from_branch_id <> to_branch_id))
        );

        ALTER TABLE stock_branch_transfer ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_branch_transfer_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_branch_transfer_line (
            id bigint NOT NULL,
            stock_branch_transfer_id bigint NOT NULL,
            part_id bigint NOT NULL,
            qty numeric(12,3) NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT stock_branch_transfer_line_qty_check CHECK ((qty > (0)::numeric))
        );

        ALTER TABLE stock_branch_transfer_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_branch_transfer_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_loan (
            id bigint NOT NULL,
            loan_date date NOT NULL,
            branch_id bigint NOT NULL,
            ref_no text,
            remarks text,
            created_by bigint,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        ALTER TABLE stock_loan ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_loan_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_loan_line (
            id bigint NOT NULL,
            stock_loan_id bigint NOT NULL,
            part_id bigint NOT NULL,
            dr_cr character(1) NOT NULL,
            qty numeric(12,3) NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            loan_to text NOT NULL,
            CONSTRAINT stock_loan_line_dr_cr_check CHECK ((dr_cr = ANY (ARRAY['D'::bpchar, 'C'::bpchar]))),
            CONSTRAINT stock_loan_line_qty_check CHECK ((qty > (0)::numeric))
        );

        ALTER TABLE stock_loan_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_loan_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_opening_balance (
            id bigint NOT NULL,
            entry_date date NOT NULL,
            ref_no text,
            branch_id bigint NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now()
        );

        ALTER TABLE stock_opening_balance ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_opening_balance_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_opening_balance_line (
            id bigint NOT NULL,
            stock_opening_balance_id bigint NOT NULL,
            part_id bigint NOT NULL,
            qty numeric(12,3) NOT NULL,
            unit_cost numeric(12,2),
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT stock_opening_balance_line_qty_check CHECK ((qty > (0)::numeric))
        );

        ALTER TABLE stock_opening_balance_line ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_opening_balance_line_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_snapshot (
            snapshot_date date NOT NULL,
            part_id bigint NOT NULL,
            branch_id bigint NOT NULL,
            opening numeric(12,3) DEFAULT 0 NOT NULL,
            closing numeric(12,3) DEFAULT 0 NOT NULL,
            purchase_in numeric(12,3) DEFAULT 0 NOT NULL,
            purchase_out numeric(12,3) DEFAULT 0 NOT NULL,
            sales_in numeric(12,3) DEFAULT 0 NOT NULL,
            sales_out numeric(12,3) DEFAULT 0 NOT NULL,
            adjust_in numeric(12,3) DEFAULT 0 NOT NULL,
            adjust_out numeric(12,3) DEFAULT 0 NOT NULL,
            loan_in numeric(12,3) DEFAULT 0 NOT NULL,
            loan_out numeric(12,3) DEFAULT 0 NOT NULL,
            branch_transfer_in numeric(12,3) DEFAULT 0 NOT NULL,
            branch_transfer_out numeric(12,3) DEFAULT 0 NOT NULL
        );

        CREATE TABLE stock_transaction (
            id bigint NOT NULL,
            part_id bigint NOT NULL,
            branch_id bigint NOT NULL,
            stock_transaction_type_id smallint NOT NULL,
            transaction_date date NOT NULL,
            dr_cr character(1) NOT NULL,
            qty numeric(12,3) NOT NULL,
            unit_cost numeric(12,2),
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            purchase_line_id bigint,
            sales_line_id bigint,
            stock_adjustment_line_id bigint,
            job_part_used_id bigint,
            stock_branch_transfer_line_id bigint,
            stock_loan_line_id bigint,
            stock_opening_balance_line_id bigint,
            CONSTRAINT stock_transaction_check CHECK ((((((((((purchase_line_id IS NOT NULL))::integer + ((sales_line_id IS NOT NULL))::integer) + ((stock_adjustment_line_id IS NOT NULL))::integer) + ((job_part_used_id IS NOT NULL))::integer) + ((stock_branch_transfer_line_id IS NOT NULL))::integer) + ((stock_loan_line_id IS NOT NULL))::integer) + ((stock_opening_balance_line_id IS NOT NULL))::integer) = 1)),
            CONSTRAINT stock_transaction_dr_cr_check CHECK ((dr_cr = ANY (ARRAY['D'::bpchar, 'C'::bpchar]))),
            CONSTRAINT stock_transaction_qty_check CHECK ((qty > (0)::numeric))
        );

        ALTER TABLE stock_transaction ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME stock_transaction_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE stock_transaction_type (
            id smallint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            dr_cr character(1) NOT NULL,
            description text,
            is_active boolean DEFAULT true NOT NULL,
            is_system boolean NOT NULL,
            CONSTRAINT stock_transaction_type_dr_cr_check CHECK ((dr_cr = ANY (ARRAY['D'::bpchar, 'C'::bpchar])))
        );

        CREATE TABLE supplier (
            id bigint NOT NULL,
            name text NOT NULL,
            gstin text,
            pan text,
            phone text,
            email text,
            address_line1 text,
            address_line2 text,
            city text,
            state_id smallint NOT NULL,
            pincode text,
            is_active boolean DEFAULT true NOT NULL,
            remarks text,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL
        );

        ALTER TABLE supplier ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME supplier_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        CREATE TABLE technician (
            id bigint NOT NULL,
            branch_id bigint NOT NULL,
            code text NOT NULL,
            name text NOT NULL,
            phone text,
            email text,
            specialization text,
            leaving_date date,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT now() NOT NULL,
            updated_at timestamp with time zone DEFAULT now() NOT NULL,
            CONSTRAINT technician_code_check CHECK ((code ~ '^[A-Z0-9_]+$'::text))
        );

        ALTER TABLE technician ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
            SEQUENCE NAME technician_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );

        ALTER TABLE ONLY additional_charge
            ADD CONSTRAINT additional_charge_name_key UNIQUE (name);

        ALTER TABLE ONLY additional_charge
            ADD CONSTRAINT additional_charge_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY app_setting
            ADD CONSTRAINT app_setting_key_uidx UNIQUE (setting_key);

        ALTER TABLE ONLY app_setting
            ADD CONSTRAINT app_setting_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY branch
            ADD CONSTRAINT branch_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY brand
            ADD CONSTRAINT brand_code_key UNIQUE (code);

        ALTER TABLE ONLY brand
            ADD CONSTRAINT brand_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY customer_contact
            ADD CONSTRAINT customer_contact_full_name_mobile_key UNIQUE (full_name, mobile);

        ALTER TABLE ONLY customer_contact
            ADD CONSTRAINT customer_contact_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY customer_type
            ADD CONSTRAINT customer_type_code_uidx UNIQUE (code);

        ALTER TABLE ONLY customer_type
            ADD CONSTRAINT customer_type_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY division
            ADD CONSTRAINT division_branch_id_code_key UNIQUE (branch_id, code);

        ALTER TABLE ONLY division
            ADD CONSTRAINT division_branch_id_name_key UNIQUE (branch_id, name);

        ALTER TABLE division
            ADD CONSTRAINT division_code_check CHECK ((code ~ '^[A-Z0-9_]+$'::text)) NOT VALID;

        ALTER TABLE ONLY division
            ADD CONSTRAINT division_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY document_sequence
            ADD CONSTRAINT document_sequence_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY document_type
            ADD CONSTRAINT document_type_code_uidx UNIQUE (code);

        ALTER TABLE ONLY document_type
            ADD CONSTRAINT document_type_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY financial_year
            ADD CONSTRAINT financial_year_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_additional_charge
            ADD CONSTRAINT job_additional_charge_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_branch_job_no_uidx UNIQUE (branch_id, job_no);

        ALTER TABLE ONLY job_delivery_manner
            ADD CONSTRAINT job_delivery_manner_code_uidx UNIQUE (code);

        ALTER TABLE ONLY job_delivery_manner
            ADD CONSTRAINT job_delivery_manner_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_image_doc
            ADD CONSTRAINT job_image_doc_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_invoice
            ADD CONSTRAINT job_invoice_invoice_no_key UNIQUE (invoice_no);

        ALTER TABLE ONLY job_invoice
            ADD CONSTRAINT job_invoice_job_id_uidx UNIQUE (job_id);

        ALTER TABLE ONLY job_invoice_line
            ADD CONSTRAINT job_invoice_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_invoice
            ADD CONSTRAINT job_invoice_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_no_uidx UNIQUE (job_no);

        ALTER TABLE ONLY job_part_used
            ADD CONSTRAINT job_part_used_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_payment
            ADD CONSTRAINT job_payment_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_receive_condition
            ADD CONSTRAINT job_receive_condition_code_uidx UNIQUE (code);

        ALTER TABLE ONLY job_receive_condition
            ADD CONSTRAINT job_receive_condition_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_receive_manner
            ADD CONSTRAINT job_receive_manner_code_uidx UNIQUE (code);

        ALTER TABLE ONLY job_receive_manner
            ADD CONSTRAINT job_receive_manner_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_status
            ADD CONSTRAINT job_status_code_uidx UNIQUE (code);

        ALTER TABLE ONLY job_status
            ADD CONSTRAINT job_status_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_transaction
            ADD CONSTRAINT job_transaction_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY job_type
            ADD CONSTRAINT job_type_code_uidx UNIQUE (code);

        ALTER TABLE ONLY job_type
            ADD CONSTRAINT job_type_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY product_brand_model
            ADD CONSTRAINT pbm_unique_model UNIQUE (product_id, brand_id, model_name);

        ALTER TABLE ONLY product_brand_model
            ADD CONSTRAINT product_brand_model_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY product
            ADD CONSTRAINT product_name_key UNIQUE (name);

        ALTER TABLE ONLY product
            ADD CONSTRAINT product_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY purchase_invoice_line
            ADD CONSTRAINT purchase_invoice_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY purchase_invoice
            ADD CONSTRAINT purchase_invoice_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY purchase_invoice
            ADD CONSTRAINT purchase_invoice_supplier_no_uidx UNIQUE (supplier_id, invoice_no);

        ALTER TABLE ONLY sales_invoice
            ADD CONSTRAINT sales_invoice_division_id_invoice_no_key UNIQUE (division_id, invoice_no);

        ALTER TABLE ONLY sales_invoice_line
            ADD CONSTRAINT sales_invoice_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY sales_invoice
            ADD CONSTRAINT sales_invoice_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY spare_part_master
            ADD CONSTRAINT spare_part_code_brand_unique UNIQUE (brand_id, part_code);

        ALTER TABLE ONLY spare_part_master
            ADD CONSTRAINT spare_part_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY state
            ADD CONSTRAINT state_code_uidx UNIQUE (code);

        ALTER TABLE ONLY state
            ADD CONSTRAINT state_name_uidx UNIQUE (name);

        ALTER TABLE ONLY state
            ADD CONSTRAINT state_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_adjustment_line
            ADD CONSTRAINT stock_adjustment_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_adjustment
            ADD CONSTRAINT stock_adjustment_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_balance
            ADD CONSTRAINT stock_balance_pkey PRIMARY KEY (part_id, branch_id);

        ALTER TABLE ONLY stock_branch_transfer_line
            ADD CONSTRAINT stock_branch_transfer_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_branch_transfer
            ADD CONSTRAINT stock_branch_transfer_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_loan_line
            ADD CONSTRAINT stock_loan_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_loan
            ADD CONSTRAINT stock_loan_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_location_change
            ADD CONSTRAINT stock_location_change_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_location_master
            ADD CONSTRAINT stock_location_master_branch_id_key UNIQUE (branch_id);

        ALTER TABLE ONLY stock_location_master
            ADD CONSTRAINT stock_location_master_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_opening_balance
            ADD CONSTRAINT stock_opening_balance_branch_id_key UNIQUE (branch_id);

        ALTER TABLE ONLY stock_opening_balance_line
            ADD CONSTRAINT stock_opening_balance_line_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_opening_balance
            ADD CONSTRAINT stock_opening_balance_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_snapshot
            ADD CONSTRAINT stock_snapshot_pkey PRIMARY KEY (snapshot_date, part_id, branch_id);

        ALTER TABLE ONLY stock_snapshot
            ADD CONSTRAINT stock_snapshot_snapshot_date_part_id_branch_id_key UNIQUE (snapshot_date, part_id, branch_id);

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY stock_transaction_type
            ADD CONSTRAINT stock_transaction_type_code_uidx UNIQUE (code);

        ALTER TABLE ONLY stock_transaction_type
            ADD CONSTRAINT stock_transaction_type_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY supplier
            ADD CONSTRAINT supplier_name_key UNIQUE (name);

        ALTER TABLE ONLY supplier
            ADD CONSTRAINT supplier_pkey PRIMARY KEY (id);

        ALTER TABLE ONLY technician
            ADD CONSTRAINT technician_bu_code_uidx UNIQUE (branch_id, code);

        ALTER TABLE ONLY technician
            ADD CONSTRAINT technician_pkey PRIMARY KEY (id);

        CREATE INDEX branch_state_idx ON branch USING btree (state_id);

        CREATE INDEX customer_contact_email_idx ON customer_contact USING btree (email) WITH (deduplicate_items='true');

        CREATE INDEX division_branch_id_is_active_idx ON division USING btree (branch_id, is_active) WITH (deduplicate_items='true');

        CREATE INDEX division_code_idx ON division USING btree (code) WITH (deduplicate_items='true');

        CREATE UNIQUE INDEX document_sequence_unique ON document_sequence USING btree (document_type_id, branch_id, COALESCE(division_id, (0)::bigint));

        CREATE INDEX idx_customer_contact_mobile ON customer_contact USING btree (mobile);

        CREATE INDEX idx_job_delivery_date ON job USING btree (delivery_date);

        CREATE INDEX idx_job_division ON job USING btree (division_id);

        CREATE INDEX idx_job_invoice_job ON job_invoice USING btree (job_id);

        CREATE INDEX idx_job_invoice_line_invoice ON job_invoice_line USING btree (job_invoice_id);

        CREATE INDEX idx_job_invoice_line_part ON job_invoice_line USING btree (part_code);

        CREATE INDEX idx_job_part_used_job ON job_part_used USING btree (job_id);

        CREATE INDEX idx_job_part_used_part ON job_part_used USING btree (part_id);

        CREATE INDEX idx_job_payment_date ON job_payment USING btree (payment_date);

        CREATE INDEX idx_job_payment_job ON job_payment USING btree (job_id);

        CREATE INDEX idx_job_transaction_job_id ON job_transaction USING btree (job_id);

        CREATE INDEX idx_job_transaction_performed_at ON job_transaction USING btree (performed_at);

        CREATE INDEX idx_job_transaction_status ON job_transaction USING btree (status_id);

        CREATE INDEX idx_purchase_invoice_line_spare_part ON purchase_invoice_line USING btree (part_id);

        CREATE INDEX idx_purchase_invoice_supplier ON purchase_invoice USING btree (supplier_id);

        CREATE INDEX idx_sales_invoice_customer ON sales_invoice USING btree (customer_contact_id);

        CREATE INDEX idx_sales_invoice_line_spare_part ON sales_invoice_line USING btree (part_id);

        CREATE INDEX idx_stock_adj_date ON stock_adjustment USING btree (adjustment_date);

        CREATE INDEX idx_stock_adj_line_adj_id ON stock_adjustment_line USING btree (stock_adjustment_id);

        CREATE INDEX idx_stock_adj_line_part ON stock_adjustment_line USING btree (part_id);

        CREATE INDEX job_alternate_job_no_idx ON job USING btree (alternate_job_no) WITH (deduplicate_items='true');

        CREATE INDEX job_batch_no_idx ON job USING btree (batch_no) WITH (deduplicate_items='true');

        CREATE INDEX job_branch_idx ON job USING btree (branch_id);

        CREATE INDEX job_customer_idx ON job USING btree (customer_contact_id);

        CREATE INDEX job_invoice_is_posted_idx ON job_invoice USING btree (is_posted) WITH (deduplicate_items='true');

        CREATE INDEX job_is_igst_idx ON job USING btree (is_igst) WITH (deduplicate_items='true');

        CREATE INDEX job_job_date_idx ON job USING btree (job_date);

        CREATE INDEX job_payment_is_posted_idx ON job_payment USING btree (is_posted) WITH (deduplicate_items='true');

        CREATE INDEX job_payment_receipt_no_idx ON job_payment USING btree (receipt_no) WITH (deduplicate_items='true');

        CREATE INDEX job_product_brand_model_id_idx ON job USING btree (product_brand_model_id) WITH (deduplicate_items='true');

        CREATE INDEX job_status_idx ON job USING btree (job_status_id);

        CREATE INDEX job_technician_idx ON job USING btree (technician_id);

        CREATE INDEX job_transaction_transaction_date_idx ON job_transaction USING btree (transaction_date) WITH (deduplicate_items='true');

        CREATE INDEX purchase_invoice_is_posted_idx ON purchase_invoice USING btree (is_posted) WITH (deduplicate_items='true');

        CREATE INDEX sales_invoice_is_posted_idx ON sales_invoice USING btree (is_posted) WITH (deduplicate_items='true');

        CREATE INDEX spare_part_master_category_idx ON spare_part_master USING btree (category) WITH (deduplicate_items='true');

        CREATE INDEX spare_part_master_is_active_part_code_idx ON spare_part_master USING btree (part_code) WHERE (is_active = true);

        CREATE INDEX spare_part_master_model_idx ON spare_part_master USING btree (model) WITH (deduplicate_items='true');

        CREATE INDEX spare_part_master_part_code_idx ON spare_part_master USING btree (part_code) WITH (deduplicate_items='true');

        CREATE INDEX spare_part_master_part_description_idx ON spare_part_master USING btree (part_description) WITH (deduplicate_items='true');

        CREATE INDEX spare_part_master_part_name_idx ON spare_part_master USING btree (part_name) WITH (deduplicate_items='true');

        CREATE INDEX stock_balance_location_id_idx ON stock_balance USING btree (location_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_branch_transfer_from_branch_id_idx ON stock_branch_transfer USING btree (from_branch_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_branch_transfer_line_part_id_idx ON stock_branch_transfer_line USING btree (part_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_branch_transfer_line_stock_branch_transfer_id_idx ON stock_branch_transfer_line USING btree (stock_branch_transfer_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_branch_transfer_to_branch_id_idx ON stock_branch_transfer USING btree (to_branch_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_branch_transfer_transfer_date_idx ON stock_branch_transfer USING btree (transfer_date) WITH (deduplicate_items='true');

        CREATE INDEX stock_loan_branch_id_idx ON stock_loan USING btree (branch_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_loan_line_part_id_idx ON stock_loan_line USING btree (part_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_loan_line_stock_loan_id_idx ON stock_loan_line USING btree (stock_loan_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_loan_loan_date_idx ON stock_loan USING btree (loan_date) WITH (deduplicate_items='true');

        CREATE INDEX stock_location_change_part_id_branch_id_idx ON stock_location_change USING btree (part_id, branch_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_location_change_transaction_date_idx ON stock_location_change USING btree (transaction_date) WITH (deduplicate_items='true');

        CREATE INDEX stock_transaction_part_id_branch_id_transaction_date_idx ON stock_transaction USING btree (part_id, branch_id, transaction_date) WITH (deduplicate_items='true');

        CREATE INDEX stock_transaction_part_id_idx ON stock_transaction USING btree (part_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_transaction_stock_transaction_type_id_idx ON stock_transaction USING btree (stock_transaction_type_id) WITH (deduplicate_items='true');

        CREATE INDEX stock_transaction_transaction_date_idx ON stock_transaction USING btree (transaction_date DESC) WITH (deduplicate_items='true');

        CREATE INDEX technician_phone_idx ON technician USING btree (phone);

        CREATE TRIGGER trg_stock_balance_delete AFTER DELETE ON stock_transaction FOR EACH ROW EXECUTE FUNCTION fn_maintain_stock_balance();

        CREATE TRIGGER trg_stock_balance_insert AFTER INSERT ON stock_transaction FOR EACH ROW EXECUTE FUNCTION fn_maintain_stock_balance();

        CREATE TRIGGER trg_stock_balance_update AFTER UPDATE ON stock_transaction FOR EACH ROW EXECUTE FUNCTION fn_maintain_stock_balance();

        ALTER TABLE ONLY branch
            ADD CONSTRAINT branch_state_fk FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY customer_contact
            ADD CONSTRAINT customer_contact_state_fk FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY customer_contact
            ADD CONSTRAINT customer_contact_type_fk FOREIGN KEY (customer_type_id) REFERENCES customer_type(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY division
            ADD CONSTRAINT division_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY division
            ADD CONSTRAINT division_state_fk FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY document_sequence
            ADD CONSTRAINT document_sequence_branch_fk FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY document_sequence
            ADD CONSTRAINT document_sequence_type_fk FOREIGN KEY (document_type_id) REFERENCES document_type(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job_additional_charge
            ADD CONSTRAINT job_additional_charge_job_id_fkey FOREIGN KEY (job_id) REFERENCES job(id) ON DELETE CASCADE;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_branch_fk FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_customer_fk FOREIGN KEY (customer_contact_id) REFERENCES customer_contact(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_division_id_fkey FOREIGN KEY (division_id) REFERENCES division(id);

        ALTER TABLE ONLY job_image_doc
            ADD CONSTRAINT job_image_doc_job_id_fkey FOREIGN KEY (job_id) REFERENCES job(id);

        ALTER TABLE ONLY job_invoice
            ADD CONSTRAINT job_invoice_job_fk FOREIGN KEY (job_id) REFERENCES job(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job_invoice_line
            ADD CONSTRAINT job_invoice_line_invoice_fk FOREIGN KEY (job_invoice_id) REFERENCES job_invoice(id) ON DELETE CASCADE;

        ALTER TABLE ONLY job_part_used
            ADD CONSTRAINT job_part_used_job_fk FOREIGN KEY (job_id) REFERENCES job(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job_part_used
            ADD CONSTRAINT job_part_used_part_fk FOREIGN KEY (part_id) REFERENCES spare_part_master(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job_payment
            ADD CONSTRAINT job_payment_job_fk FOREIGN KEY (job_id) REFERENCES job(id) ON DELETE CASCADE;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_product_brand_model_fk FOREIGN KEY (product_brand_model_id) REFERENCES product_brand_model(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_receive_condition_fk FOREIGN KEY (job_receive_condition_id) REFERENCES job_receive_condition(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_receive_manner_fk FOREIGN KEY (job_receive_manner_id) REFERENCES job_receive_manner(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_status_fk FOREIGN KEY (job_status_id) REFERENCES job_status(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_technician_fk FOREIGN KEY (technician_id) REFERENCES technician(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job_transaction
            ADD CONSTRAINT job_transaction_job_fk FOREIGN KEY (job_id) REFERENCES job(id) ON DELETE CASCADE;

        ALTER TABLE ONLY job_transaction
            ADD CONSTRAINT job_transaction_status_fk FOREIGN KEY (status_id) REFERENCES job_status(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job_transaction
            ADD CONSTRAINT job_transaction_technician_fk FOREIGN KEY (technician_id) REFERENCES technician(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY job
            ADD CONSTRAINT job_type_fk FOREIGN KEY (job_type_id) REFERENCES job_type(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY product_brand_model
            ADD CONSTRAINT pbm_brand_fk FOREIGN KEY (brand_id) REFERENCES brand(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY product_brand_model
            ADD CONSTRAINT pbm_product_fk FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY purchase_invoice
            ADD CONSTRAINT purchase_invoice_branch_fk FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY purchase_invoice
            ADD CONSTRAINT purchase_invoice_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brand(id);

        ALTER TABLE ONLY purchase_invoice
            ADD CONSTRAINT purchase_invoice_division_id_fkey FOREIGN KEY (division_id) REFERENCES division(id) NOT VALID;

        ALTER TABLE ONLY purchase_invoice_line
            ADD CONSTRAINT purchase_invoice_line_invoice_fk FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoice(id) ON DELETE CASCADE;

        ALTER TABLE ONLY purchase_invoice_line
            ADD CONSTRAINT purchase_invoice_line_part_fk FOREIGN KEY (part_id) REFERENCES spare_part_master(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY purchase_invoice
            ADD CONSTRAINT purchase_invoice_supplier_fk FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY sales_invoice
            ADD CONSTRAINT sales_invoice_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brand(id) NOT VALID;

        ALTER TABLE ONLY sales_invoice
            ADD CONSTRAINT sales_invoice_customer_fk FOREIGN KEY (customer_contact_id) REFERENCES customer_contact(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY sales_invoice
            ADD CONSTRAINT sales_invoice_division_id_fkey FOREIGN KEY (division_id) REFERENCES division(id);

        ALTER TABLE ONLY sales_invoice_line
            ADD CONSTRAINT sales_invoice_line_invoice_fk FOREIGN KEY (sales_invoice_id) REFERENCES sales_invoice(id) ON DELETE CASCADE;

        ALTER TABLE ONLY sales_invoice_line
            ADD CONSTRAINT sales_invoice_line_part_fk FOREIGN KEY (part_id) REFERENCES spare_part_master(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY spare_part_master
            ADD CONSTRAINT spare_part_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brand(id);

        ALTER TABLE ONLY stock_adjustment
            ADD CONSTRAINT stock_adjustment_branch_fk FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY stock_adjustment_line
            ADD CONSTRAINT stock_adjustment_line_adjustment_fk FOREIGN KEY (stock_adjustment_id) REFERENCES stock_adjustment(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_adjustment_line
            ADD CONSTRAINT stock_adjustment_line_spare_part_fk FOREIGN KEY (part_id) REFERENCES spare_part_master(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY stock_balance
            ADD CONSTRAINT stock_balance_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY stock_balance
            ADD CONSTRAINT stock_balance_location_id_fkey FOREIGN KEY (location_id) REFERENCES stock_location_master(id) NOT VALID;

        ALTER TABLE ONLY stock_balance
            ADD CONSTRAINT stock_balance_part_id_fkey FOREIGN KEY (part_id) REFERENCES spare_part_master(id);

        ALTER TABLE ONLY stock_branch_transfer
            ADD CONSTRAINT stock_branch_transfer_from_branch_id_fkey FOREIGN KEY (from_branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY stock_branch_transfer_line
            ADD CONSTRAINT stock_branch_transfer_line_part_id_fkey FOREIGN KEY (part_id) REFERENCES spare_part_master(id);

        ALTER TABLE ONLY stock_branch_transfer_line
            ADD CONSTRAINT stock_branch_transfer_line_stock_branch_transfer_id_fkey FOREIGN KEY (stock_branch_transfer_id) REFERENCES stock_branch_transfer(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_branch_transfer
            ADD CONSTRAINT stock_branch_transfer_to_branch_id_fkey FOREIGN KEY (to_branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY stock_loan
            ADD CONSTRAINT stock_loan_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY stock_loan_line
            ADD CONSTRAINT stock_loan_line_part_id_fkey FOREIGN KEY (part_id) REFERENCES spare_part_master(id);

        ALTER TABLE ONLY stock_loan_line
            ADD CONSTRAINT stock_loan_line_stock_loan_id_fkey FOREIGN KEY (stock_loan_id) REFERENCES stock_loan(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_location_change
            ADD CONSTRAINT stock_location_change_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id) NOT VALID;

        ALTER TABLE ONLY stock_location_change
            ADD CONSTRAINT stock_location_change_part_id_fkey FOREIGN KEY (part_id) REFERENCES spare_part_master(id) NOT VALID;

        ALTER TABLE ONLY stock_location_change
            ADD CONSTRAINT stock_location_change_to_location_id_fkey FOREIGN KEY (to_location_id) REFERENCES stock_location_master(id) NOT VALID;

        ALTER TABLE ONLY stock_location_master
            ADD CONSTRAINT stock_location_master_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id) NOT VALID;

        ALTER TABLE ONLY stock_opening_balance
            ADD CONSTRAINT stock_opening_balance_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY stock_opening_balance_line
            ADD CONSTRAINT stock_opening_balance_line_part_id_fkey FOREIGN KEY (part_id) REFERENCES spare_part_master(id);

        ALTER TABLE ONLY stock_opening_balance_line
            ADD CONSTRAINT stock_opening_balance_line_stock_opening_balance_id_fkey FOREIGN KEY (stock_opening_balance_id) REFERENCES stock_opening_balance(id) ON DELETE CASCADE NOT VALID;

        ALTER TABLE ONLY stock_snapshot
            ADD CONSTRAINT stock_snapshot_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES branch(id);

        ALTER TABLE ONLY stock_snapshot
            ADD CONSTRAINT stock_snapshot_part_id_fkey FOREIGN KEY (part_id) REFERENCES spare_part_master(id);

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_branch_fk FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_job_part_used_id_fkey FOREIGN KEY (job_part_used_id) REFERENCES job_part_used(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_part_id_fk FOREIGN KEY (part_id) REFERENCES spare_part_master(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_purchase_line_id_fkey FOREIGN KEY (purchase_line_id) REFERENCES purchase_invoice_line(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_sales_line_id_fkey FOREIGN KEY (sales_line_id) REFERENCES sales_invoice_line(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_stock_adjustment_line_id_fkey FOREIGN KEY (stock_adjustment_line_id) REFERENCES stock_adjustment_line(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_stock_branch_transfer_line_id_fkey FOREIGN KEY (stock_branch_transfer_line_id) REFERENCES stock_branch_transfer_line(id);

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_stock_loan_line_id_fkey FOREIGN KEY (stock_loan_line_id) REFERENCES stock_loan_line(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_stock_opening_balance_line_id_fkey FOREIGN KEY (stock_opening_balance_line_id) REFERENCES stock_opening_balance_line(id) ON DELETE CASCADE;

        ALTER TABLE ONLY stock_transaction
            ADD CONSTRAINT stock_transaction_type_fk FOREIGN KEY (stock_transaction_type_id) REFERENCES stock_transaction_type(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY supplier
            ADD CONSTRAINT supplier_state_fk FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE RESTRICT;

        ALTER TABLE ONLY technician
            ADD CONSTRAINT technician_branch_fk FOREIGN KEY (branch_id) REFERENCES branch(id) ON DELETE RESTRICT;
    """
