export const ROUTES = {
	home: "/",
	login: "/login",
	resetPassword: "/reset-password",
	client: {
		admin: "/client/admin",
		configurations: "/client/configurations",
		custom: "/client/custom",
		// Fixed by the approved staff-alert template's button prefix (plan Part B2).
		customEwRef: "/client/custom/ew/:ref",
		inventory: "/client/inventory",
		jobs: "/client/jobs",
		masters: "/client/masters",
		reports: "/client/reports",
		root: "/client",
	},
	admin: {
		audit: "/admin/audit",
		businessUnits: "/admin/business-units",
		enquiries: "/admin/enquiries",
		roles: "/admin/roles",
		root: "/admin",
		settings: "/admin/settings",
		subscriptions: "/admin/subscriptions",
		users: "/admin/users",
	},
	superAdmin: {
		audit: "/super-admin/audit",
		clients: "/super-admin/clients",
		enquiries: "/super-admin/enquiries",
		root: "/super-admin",
		settings: "/super-admin/settings",
		usage: "/super-admin/usage",
	},
} as const;
