export const SQL_MAP = {
    CHECK_CLIENT_CODE_EXISTS: "CHECK_CLIENT_CODE_EXISTS",
    CHECK_CLIENT_NAME_EXISTS: "CHECK_CLIENT_NAME_EXISTS",
    CHECK_DB_NAME_EXISTS: "CHECK_DB_NAME_EXISTS",
    GET_CLIENT_DB_NAMES: "GET_CLIENT_DB_NAMES",
}