export const SQL_MAP = {
    CHECK_ADMIN_EMAIL_EXISTS: "CHECK_ADMIN_EMAIL_EXISTS",
    CHECK_ADMIN_EMAIL_EXISTS_EXCLUDE_ID: "CHECK_ADMIN_EMAIL_EXISTS_EXCLUDE_ID",
    CHECK_ADMIN_USERNAME_EXISTS: "CHECK_ADMIN_USERNAME_EXISTS",
    CHECK_CLIENT_CODE_EXISTS: "CHECK_CLIENT_CODE_EXISTS",
    CHECK_CLIENT_CODE_EXISTS_EXCLUDE_ID: "CHECK_CLIENT_CODE_EXISTS_EXCLUDE_ID",
    CHECK_CLIENT_NAME_EXISTS: "CHECK_CLIENT_NAME_EXISTS",
    CHECK_CLIENT_NAME_EXISTS_EXCLUDE_ID: "CHECK_CLIENT_NAME_EXISTS_EXCLUDE_ID",
    CHECK_DB_NAME_EXISTS: "CHECK_DB_NAME_EXISTS",
    CHECK_ROLE_SEED_EXISTS: "CHECK_ROLE_SEED_EXISTS",
    GET_CLIENT_DB_NAMES: "GET_CLIENT_DB_NAMES",
}