"""
GraphQL Mutation resolvers.
"""

from typing import Any
from ariadne import MutationType
from app.logger import logger
from app.exceptions import ValidationException, GraphQLException, AppMessages
from app.graphql.resolvers.mutation_helper import (
    resolve_create_admin_user_helper,
    resolve_create_service_db_helper,
    resolve_delete_client_helper,
    resolve_drop_database_helper,
    resolve_generic_update_helper,
    resolve_mail_admin_credentials_helper,
    resolve_set_admin_user_active_helper,
    resolve_update_admin_user_helper,
)
# from app.graphql.pubsub import pubsub


# Create MutationType instance
mutation = MutationType()


@mutation.field("deleteClient")
async def resolve_delete_client(_, info, client_id: int) -> Any:
    try:
        return await resolve_delete_client_helper(client_id)
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error deleting client: {str(e)}")
        raise GraphQLException(
            message=AppMessages.OPERATION_FAILED, extensions={"details": str(e)}
        )


@mutation.field("createAdminUser")
async def resolve_create_admin_user(
    _,
    info,
    db_name: str,
    email: str,
    full_name: str,
    username: str,
    mobile: str | None = None,
) -> Any:
    """Create a new admin user in the security schema of a client database.

    Password is auto-generated by the server and emailed to the user.

    Args:
        db_name:   Target service database name.
        email:     User email. Credentials are sent here.
        full_name: User full name.
        username:  Username supplied by the SA.
        mobile:    Mobile number (optional).

    Returns:
        Dict with the newly created user id.
    """
    try:
        return await resolve_create_admin_user_helper(
            db_name=db_name,
            email=email,
            full_name=full_name,
            mobile=mobile,
            username=username,
        )
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error creating admin user: {str(e)}")
        raise GraphQLException(
            message=AppMessages.OPERATION_FAILED, extensions={"details": str(e)}
        )


@mutation.field("createServiceDb")
async def resolve_create_service_db(_, info, client_id: int, db_name: str) -> Any:
    """Create a new service database for a client.

    Args:
        client_id: ID of the client in the client database.
        db_name:   Name of the new PostgreSQL database to create.

    Returns:
        Dict with client id and db_name on success.
    """
    try:
        return await resolve_create_service_db_helper(client_id, db_name)
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error creating service database: {str(e)}")
        raise GraphQLException(
            message=AppMessages.OPERATION_FAILED, extensions={"details": str(e)}
        )


@mutation.field("dropDatabase")
async def resolve_drop_database(_, info, db_name: str) -> Any:
    """Physically drop an orphan PostgreSQL database.

    Args:
        db_name: Name of the orphan database to drop.

    Returns:
        Dict with the dropped db_name.
    """
    try:
        return await resolve_drop_database_helper(db_name)
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error dropping database: {str(e)}")
        raise GraphQLException(
            message=AppMessages.DB_DROP_FAILED, extensions={"details": str(e)}
        )


@mutation.field("setAdminUserActive")
async def resolve_set_admin_user_active(_, info, db_name: str, id: int, is_active: bool) -> Any:
    try:
        return await resolve_set_admin_user_active_helper(db_name, id, is_active)
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error setting admin user active: {str(e)}")
        raise GraphQLException(
            message=AppMessages.OPERATION_FAILED, extensions={"details": str(e)}
        )


@mutation.field("updateAdminUser")
async def resolve_update_admin_user(
    _, info, db_name: str, email: str, full_name: str, id: int, mobile: str | None = None
) -> Any:
    try:
        return await resolve_update_admin_user_helper(db_name, id, full_name, email, mobile)
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error updating admin user: {str(e)}")
        raise GraphQLException(
            message=AppMessages.ADMIN_USER_UPDATE_FAILED, extensions={"details": str(e)}
        )


@mutation.field("mailAdminCredentials")
async def resolve_mail_admin_credentials(_, info, db_name: str, id: int) -> Any:
    try:
        return await resolve_mail_admin_credentials_helper(db_name, id)
    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error mailing admin credentials: {str(e)}")
        raise GraphQLException(
            message=AppMessages.OPERATION_FAILED, extensions={"details": str(e)}
        )


@mutation.field("genericUpdate")
async def resolve_generic_update(_, info, db_name="", schema="public", value="") -> Any:
    """Generic update resolver.
    Update a generic database entry.

    Args:
        db_name: Database name
        schema: Database schema (default: "public")
        value: Value to update
    Returns:
        Updated database entry data
    """
    try:
        return await resolve_generic_update_helper(db_name, schema, value)

    except ValidationException:
        raise
    except Exception as e:
        logger.error(f"Error creating customer: {str(e)}")
        raise GraphQLException(
            message=AppMessages.OPERATION_FAILED, extensions={"details": str(e)}
        )
