import type {
  ActivityLogItemType,
  AdminUserType,
  ClientType,
  PlatformMetricType,
  SettingSectionType,
  StatsType,
  SystemServiceType,
  UptimeDataPointType,
} from "./types";

// ─── Clients (Bu table) ───────────────────────────────────────────────────────

export const dummyClients: ClientType[] = [
  {
    activeAdminCount: 8,
    code: "ALP",
    created_at: new Date("2023-01-15"),
    id: 1,
    inactiveAdminCount: 1,
    is_active: true,
    name: "Alpha Corp",
    updated_at: new Date("2024-06-01"),
  },
  {
    activeAdminCount: 5,
    code: "BET",
    created_at: new Date("2024-03-10"),
    id: 2,
    inactiveAdminCount: 0,
    is_active: true,
    name: "Beta Solutions",
    updated_at: new Date("2024-12-20"),
  },
  {
    activeAdminCount: 0,
    code: "GAM",
    created_at: new Date("2022-07-22"),
    id: 3,
    inactiveAdminCount: 3,
    is_active: false,
    name: "Gamma Enterprises",
    updated_at: new Date("2025-01-10"),
  },
  {
    activeAdminCount: 4,
    code: "DEL",
    created_at: new Date("2023-11-30"),
    id: 4,
    inactiveAdminCount: 0,
    is_active: true,
    name: "Delta Services",
    updated_at: new Date("2025-08-15"),
  },
  {
    activeAdminCount: 6,
    code: "EPS",
    created_at: new Date("2021-05-05"),
    id: 5,
    inactiveAdminCount: 1,
    is_active: true,
    name: "Epsilon Tech",
    updated_at: new Date("2025-11-22"),
  },
  {
    activeAdminCount: 0,
    code: "ZET",
    created_at: new Date("2020-09-18"),
    id: 6,
    inactiveAdminCount: 2,
    is_active: false,
    name: "Zeta Industries",
    updated_at: new Date("2024-03-01"),
  },
];

export const dummyStats: StatsType = {
  activeAdminUsers: 390,
  activeBu: 110,
  inactiveAdminUsers: 30,
  inactiveBu: 10,
  totalAdminUsers: 420,
  totalBu: 120,
};

// ─── Admin Users (User + UserBuRole + Role tables) ────────────────────────────

export const dummyAdminUsers: AdminUserType[] = [
  {
    bu_id: 1,
    bu_name: "Alpha Corp",
    created_at: new Date("2023-02-01"),
    email: "sarah.johnson@alphacorp.com",
    full_name: "Sarah Johnson",
    id: 1,
    is_active: true,
    is_admin: true,
    last_login_at: new Date("2026-02-20"),
    mobile: "+91-9876543210",
    role: "ClientAdmin",
    updated_at: new Date("2026-02-20"),
    username: "sarah.johnson",
  },
  {
    bu_id: 1,
    bu_name: "Alpha Corp",
    created_at: new Date("2023-03-15"),
    email: "mike.chen@alphacorp.com",
    full_name: "Mike Chen",
    id: 2,
    is_active: true,
    is_admin: false,
    last_login_at: new Date("2026-02-18"),
    mobile: null,
    role: "Viewer",
    updated_at: new Date("2026-02-18"),
    username: "mike.chen",
  },
  {
    bu_id: 2,
    bu_name: "Beta Solutions",
    created_at: new Date("2024-04-10"),
    email: "priya.patel@betasolutions.com",
    full_name: "Priya Patel",
    id: 3,
    is_active: true,
    is_admin: true,
    last_login_at: new Date("2026-02-21"),
    mobile: "+91-9123456789",
    role: "ClientAdmin",
    updated_at: new Date("2026-02-21"),
    username: "priya.patel",
  },
  {
    bu_id: 3,
    bu_name: "Gamma Enterprises",
    created_at: new Date("2022-08-01"),
    email: "james.wilson@gamma.com",
    full_name: "James Wilson",
    id: 4,
    is_active: false,
    is_admin: true,
    last_login_at: new Date("2025-11-05"),
    mobile: null,
    role: "ClientAdmin",
    updated_at: new Date("2025-11-05"),
    username: "james.wilson",
  },
  {
    bu_id: 4,
    bu_name: "Delta Services",
    created_at: new Date("2023-12-01"),
    email: "laura.smith@deltaservices.com",
    full_name: "Laura Smith",
    id: 5,
    is_active: true,
    is_admin: false,
    last_login_at: new Date("2026-02-19"),
    mobile: "+91-9988776655",
    role: "Viewer",
    updated_at: new Date("2026-02-19"),
    username: "laura.smith",
  },
  {
    bu_id: 5,
    bu_name: "Epsilon Tech",
    created_at: new Date("2021-06-01"),
    email: "david.lee@epsilontech.com",
    full_name: "David Lee",
    id: 6,
    is_active: true,
    is_admin: true,
    last_login_at: new Date("2026-02-21"),
    mobile: "+91-9001122334",
    role: "ClientAdmin",
    updated_at: new Date("2026-02-21"),
    username: "david.lee",
  },
  {
    bu_id: 5,
    bu_name: "Epsilon Tech",
    created_at: new Date("2021-07-20"),
    email: "anna.garcia@epsilontech.com",
    full_name: "Anna Garcia",
    id: 7,
    is_active: false,
    is_admin: false,
    last_login_at: new Date("2026-01-30"),
    mobile: null,
    role: "Viewer",
    updated_at: new Date("2026-01-30"),
    username: "anna.garcia",
  },
  {
    bu_id: 6,
    bu_name: "Zeta Industries",
    created_at: new Date("2020-10-01"),
    email: "robert.kim@zetaindustries.com",
    full_name: "Robert Kim",
    id: 8,
    is_active: true,
    is_admin: true,
    last_login_at: new Date("2026-02-10"),
    mobile: "+91-9445566778",
    role: "SuperAdmin",
    updated_at: new Date("2026-02-10"),
    username: "robert.kim",
  },
];

// ─── Audit Logs ───────────────────────────────────────────────────────────────

export const dummyActivityLog: ActivityLogItemType[] = [
  {
    action: "Client Created",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log1",
    ipAddress: "192.168.1.10",
    targetName: "Beta Solutions",
    timestamp: "2026-02-21T09:15:00Z",
  },
  {
    action: "Admin Added",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log2",
    ipAddress: "192.168.1.10",
    targetName: "Priya Patel",
    timestamp: "2026-02-21T09:18:00Z",
  },
  {
    action: "Login",
    actorEmail: "sarah.johnson@alphacorp.com",
    actorName: "Sarah Johnson",
    id: "log3",
    ipAddress: "203.0.113.45",
    targetName: "Sarah Johnson",
    timestamp: "2026-02-21T08:45:00Z",
  },
  {
    action: "Settings Changed",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log4",
    ipAddress: "192.168.1.10",
    targetName: "Email Notifications",
    timestamp: "2026-02-20T16:30:00Z",
  },
  {
    action: "Client Disabled",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log5",
    ipAddress: "192.168.1.10",
    targetName: "Gamma Enterprises",
    timestamp: "2026-02-20T14:10:00Z",
  },
  {
    action: "Admin Deactivated",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log6",
    ipAddress: "192.168.1.10",
    targetName: "James Wilson",
    timestamp: "2026-02-20T14:12:00Z",
  },
  {
    action: "Password Reset",
    actorEmail: "david.lee@epsilontech.com",
    actorName: "David Lee",
    id: "log7",
    ipAddress: "10.0.0.55",
    targetName: "David Lee",
    timestamp: "2026-02-20T11:05:00Z",
  },
  {
    action: "Login",
    actorEmail: "david.lee@epsilontech.com",
    actorName: "David Lee",
    id: "log8",
    ipAddress: "10.0.0.55",
    targetName: "David Lee",
    timestamp: "2026-02-20T11:07:00Z",
  },
  {
    action: "Admin Added",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log9",
    ipAddress: "192.168.1.10",
    targetName: "Laura Smith",
    timestamp: "2026-02-19T10:00:00Z",
  },
  {
    action: "Settings Changed",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log10",
    ipAddress: "192.168.1.10",
    targetName: "Security Policy",
    timestamp: "2026-02-18T15:45:00Z",
  },
];

// ─── System Health ────────────────────────────────────────────────────────────

export const dummySystemServices: SystemServiceType[] = [
  {
    id: "svc1",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "API Gateway",
    responseTime: 42,
    status: "Healthy",
    uptime: 99.98,
  },
  {
    id: "svc2",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "Auth Service",
    responseTime: 38,
    status: "Healthy",
    uptime: 99.95,
  },
  {
    id: "svc3",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "Database",
    responseTime: 120,
    status: "Degraded",
    uptime: 98.72,
  },
  {
    id: "svc4",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "Email Service",
    responseTime: 210,
    status: "Degraded",
    uptime: 97.5,
  },
];

export const dummyPlatformMetrics: PlatformMetricType[] = [
  {
    change: 12,
    id: "m1",
    label: "API Requests Today",
    trend: "up",
    unit: "",
    value: "84,320",
  },
  {
    change: 5,
    id: "m2",
    label: "Active Sessions",
    trend: "up",
    unit: "",
    value: "1,248",
  },
  {
    change: -3,
    id: "m3",
    label: "Avg Response Time",
    trend: "down",
    unit: "ms",
    value: "68",
  },
  {
    change: 0.02,
    id: "m4",
    label: "Error Rate",
    trend: "neutral",
    unit: "%",
    value: "0.12",
  },
];

export const dummyUptimeData: UptimeDataPointType[] = [
  { day: "Feb 15", uptime: 99.98 },
  { day: "Feb 16", uptime: 99.95 },
  { day: "Feb 17", uptime: 100 },
  { day: "Feb 18", uptime: 99.8 },
  { day: "Feb 19", uptime: 98.72 },
  { day: "Feb 20", uptime: 97.5 },
  { day: "Feb 21", uptime: 98.9 },
];

// ─── System Settings ──────────────────────────────────────────────────────────

export const dummySettingSections: SettingSectionType[] = [
  {
    id: "general",
    items: [
      { key: "platformName", label: "Platform Name", value: "Service Plus" },
      { key: "supportEmail", label: "Support Email", value: "support@serviceplus.com" },
      { key: "timezone", label: "Default Timezone", value: "UTC+0 (London)" },
      { key: "dateFormat", label: "Date Format", value: "MM/DD/YYYY" },
    ],
    title: "General",
  },
  {
    id: "security",
    items: [
      { key: "mfaRequired", label: "MFA Required", value: "Enabled" },
      { key: "sessionTimeout", label: "Session Timeout", value: "30 minutes" },
      { key: "passwordPolicy", label: "Password Policy", value: "Strong (min 10 chars)" },
      { key: "ipWhitelist", label: "IP Whitelist", value: "Disabled" },
    ],
    title: "Security",
  },
  {
    id: "notifications",
    items: [
      { key: "emailAlerts", label: "Email Alerts", value: "Enabled" },
      { key: "alertRecipient", label: "Alert Recipient", value: "superadmin@platform.com" },
      { key: "clientOnboard", label: "New Client Onboard Alert", value: "Enabled" },
      { key: "serviceDown", label: "Service Down Alert", value: "Enabled" },
    ],
    title: "Notifications",
  },
  {
    id: "integrations",
    items: [
      { key: "smtpHost", label: "SMTP Host", value: "smtp.sendgrid.net" },
      { key: "smtpPort", label: "SMTP Port", value: "587" },
      { key: "slackWebhook", label: "Slack Webhook", value: "Configured" },
      { key: "ssoProvider", label: "SSO Provider", value: "Not configured" },
    ],
    title: "Integrations",
  },
];
