import type {
  ActivityLogItemType,
  AdminUserType,
  ClientType,
  PlatformMetricType,
  SettingSectionType,
  StatsType,
  SystemServiceType,
  UptimeDataPointType,
} from "./types";

// ─── Clients ──────────────────────────────────────────────────────────────────

export const dummyClients: ClientType[] = [
  {
    activeAdminCount: 8,
    clientCode: "ALP",
    clientName: "Alpha Corp",
    createdDate: "01/15/2023",
    id: "1",
    inactiveAdminCount: 1,
    status: "Active",
  },
  {
    activeAdminCount: 5,
    clientCode: "BET",
    clientName: "Beta Solutions",
    createdDate: "03/10/2024",
    id: "2",
    inactiveAdminCount: 0,
    status: "Active",
  },
  {
    activeAdminCount: 0,
    clientCode: "GAM",
    clientName: "Gamma Enterprises",
    createdDate: "07/22/2022",
    id: "3",
    inactiveAdminCount: 3,
    status: "Inactive",
  },
  {
    activeAdminCount: 4,
    clientCode: "DEL",
    clientName: "Delta Services",
    createdDate: "11/30/2023",
    id: "4",
    inactiveAdminCount: 0,
    status: "Active",
  },
  {
    activeAdminCount: 6,
    clientCode: "EPS",
    clientName: "Epsilon Tech",
    createdDate: "05/05/2021",
    id: "5",
    inactiveAdminCount: 1,
    status: "Active",
  },
  {
    activeAdminCount: 0,
    clientCode: "ZET",
    clientName: "Zeta Industries",
    createdDate: "09/18/2020",
    id: "6",
    inactiveAdminCount: 2,
    status: "Inactive",
  },
];

export const dummyStats: StatsType = {
  activeAdminUsers: 390,
  activeClients: 110,
  inactiveAdminUsers: 30,
  inactiveClients: 10,
  totalAdminUsers: 420,
  totalClients: 120,
};

// ─── Admin Users ──────────────────────────────────────────────────────────────

export const dummyAdminUsers: AdminUserType[] = [
  {
    clientId: "1",
    clientName: "Alpha Corp",
    createdDate: "02/01/2023",
    email: "sarah.johnson@alphacorp.com",
    id: "a1",
    lastLoginDate: "02/20/2026",
    name: "Sarah Johnson",
    role: "ClientAdmin",
    status: "Active",
  },
  {
    clientId: "1",
    clientName: "Alpha Corp",
    createdDate: "03/15/2023",
    email: "mike.chen@alphacorp.com",
    id: "a2",
    lastLoginDate: "02/18/2026",
    name: "Mike Chen",
    role: "Viewer",
    status: "Active",
  },
  {
    clientId: "2",
    clientName: "Beta Solutions",
    createdDate: "04/10/2024",
    email: "priya.patel@betasolutions.com",
    id: "a3",
    lastLoginDate: "02/21/2026",
    name: "Priya Patel",
    role: "ClientAdmin",
    status: "Active",
  },
  {
    clientId: "3",
    clientName: "Gamma Enterprises",
    createdDate: "08/01/2022",
    email: "james.wilson@gamma.com",
    id: "a4",
    lastLoginDate: "11/05/2025",
    name: "James Wilson",
    role: "ClientAdmin",
    status: "Inactive",
  },
  {
    clientId: "4",
    clientName: "Delta Services",
    createdDate: "12/01/2023",
    email: "laura.smith@deltaservices.com",
    id: "a5",
    lastLoginDate: "02/19/2026",
    name: "Laura Smith",
    role: "Viewer",
    status: "Active",
  },
  {
    clientId: "5",
    clientName: "Epsilon Tech",
    createdDate: "06/01/2021",
    email: "david.lee@epsilontech.com",
    id: "a6",
    lastLoginDate: "02/21/2026",
    name: "David Lee",
    role: "ClientAdmin",
    status: "Active",
  },
  {
    clientId: "5",
    clientName: "Epsilon Tech",
    createdDate: "07/20/2021",
    email: "anna.garcia@epsilontech.com",
    id: "a7",
    lastLoginDate: "01/30/2026",
    name: "Anna Garcia",
    role: "Viewer",
    status: "Inactive",
  },
  {
    clientId: "6",
    clientName: "Zeta Industries",
    createdDate: "10/01/2020",
    email: "robert.kim@zetaindustries.com",
    id: "a8",
    lastLoginDate: "02/10/2026",
    name: "Robert Kim",
    role: "SuperAdmin",
    status: "Active",
  },
];

// ─── Audit Logs ───────────────────────────────────────────────────────────────

export const dummyActivityLog: ActivityLogItemType[] = [
  {
    action: "Client Created",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log1",
    ipAddress: "192.168.1.10",
    targetName: "Beta Solutions",
    timestamp: "2026-02-21T09:15:00Z",
  },
  {
    action: "Admin Added",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log2",
    ipAddress: "192.168.1.10",
    targetName: "Priya Patel",
    timestamp: "2026-02-21T09:18:00Z",
  },
  {
    action: "Login",
    actorEmail: "sarah.johnson@alphacorp.com",
    actorName: "Sarah Johnson",
    id: "log3",
    ipAddress: "203.0.113.45",
    targetName: "Sarah Johnson",
    timestamp: "2026-02-21T08:45:00Z",
  },
  {
    action: "Settings Changed",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log4",
    ipAddress: "192.168.1.10",
    targetName: "Email Notifications",
    timestamp: "2026-02-20T16:30:00Z",
  },
  {
    action: "Client Disabled",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log5",
    ipAddress: "192.168.1.10",
    targetName: "Gamma Enterprises",
    timestamp: "2026-02-20T14:10:00Z",
  },
  {
    action: "Admin Deactivated",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log6",
    ipAddress: "192.168.1.10",
    targetName: "James Wilson",
    timestamp: "2026-02-20T14:12:00Z",
  },
  {
    action: "Password Reset",
    actorEmail: "david.lee@epsilontech.com",
    actorName: "David Lee",
    id: "log7",
    ipAddress: "10.0.0.55",
    targetName: "David Lee",
    timestamp: "2026-02-20T11:05:00Z",
  },
  {
    action: "Login",
    actorEmail: "david.lee@epsilontech.com",
    actorName: "David Lee",
    id: "log8",
    ipAddress: "10.0.0.55",
    targetName: "David Lee",
    timestamp: "2026-02-20T11:07:00Z",
  },
  {
    action: "Admin Added",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log9",
    ipAddress: "192.168.1.10",
    targetName: "Laura Smith",
    timestamp: "2026-02-19T10:00:00Z",
  },
  {
    action: "Settings Changed",
    actorEmail: "superadmin@platform.com",
    actorName: "Super Admin",
    id: "log10",
    ipAddress: "192.168.1.10",
    targetName: "Security Policy",
    timestamp: "2026-02-18T15:45:00Z",
  },
];

// ─── System Health ────────────────────────────────────────────────────────────

export const dummySystemServices: SystemServiceType[] = [
  {
    id: "svc1",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "API Gateway",
    responseTime: 42,
    status: "Healthy",
    uptime: 99.98,
  },
  {
    id: "svc2",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "Auth Service",
    responseTime: 38,
    status: "Healthy",
    uptime: 99.95,
  },
  {
    id: "svc3",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "Database",
    responseTime: 120,
    status: "Degraded",
    uptime: 98.72,
  },
  {
    id: "svc4",
    lastChecked: "2026-02-21T09:20:00Z",
    name: "Email Service",
    responseTime: 210,
    status: "Degraded",
    uptime: 97.50,
  },
];

export const dummyPlatformMetrics: PlatformMetricType[] = [
  {
    change: 12,
    id: "m1",
    label: "API Requests Today",
    trend: "up",
    unit: "",
    value: "84,320",
  },
  {
    change: 5,
    id: "m2",
    label: "Active Sessions",
    trend: "up",
    unit: "",
    value: "1,248",
  },
  {
    change: -3,
    id: "m3",
    label: "Avg Response Time",
    trend: "down",
    unit: "ms",
    value: "68",
  },
  {
    change: 0.02,
    id: "m4",
    label: "Error Rate",
    trend: "neutral",
    unit: "%",
    value: "0.12",
  },
];

export const dummyUptimeData: UptimeDataPointType[] = [
  { day: "Feb 15", uptime: 99.98 },
  { day: "Feb 16", uptime: 99.95 },
  { day: "Feb 17", uptime: 100 },
  { day: "Feb 18", uptime: 99.80 },
  { day: "Feb 19", uptime: 98.72 },
  { day: "Feb 20", uptime: 97.50 },
  { day: "Feb 21", uptime: 98.90 },
];

// ─── System Settings ──────────────────────────────────────────────────────────

export const dummySettingSections: SettingSectionType[] = [
  {
    id: "general",
    items: [
      { key: "platformName", label: "Platform Name", value: "Service Plus" },
      { key: "supportEmail", label: "Support Email", value: "support@serviceplus.com" },
      { key: "timezone", label: "Default Timezone", value: "UTC+0 (London)" },
      { key: "dateFormat", label: "Date Format", value: "MM/DD/YYYY" },
    ],
    title: "General",
  },
  {
    id: "security",
    items: [
      { key: "mfaRequired", label: "MFA Required", value: "Enabled" },
      { key: "sessionTimeout", label: "Session Timeout", value: "30 minutes" },
      { key: "passwordPolicy", label: "Password Policy", value: "Strong (min 10 chars)" },
      { key: "ipWhitelist", label: "IP Whitelist", value: "Disabled" },
    ],
    title: "Security",
  },
  {
    id: "notifications",
    items: [
      { key: "emailAlerts", label: "Email Alerts", value: "Enabled" },
      { key: "alertRecipient", label: "Alert Recipient", value: "superadmin@platform.com" },
      { key: "clientOnboard", label: "New Client Onboard Alert", value: "Enabled" },
      { key: "serviceDown", label: "Service Down Alert", value: "Enabled" },
    ],
    title: "Notifications",
  },
  {
    id: "integrations",
    items: [
      { key: "smtpHost", label: "SMTP Host", value: "smtp.sendgrid.net" },
      { key: "smtpPort", label: "SMTP Port", value: "587" },
      { key: "slackWebhook", label: "Slack Webhook", value: "Configured" },
      { key: "ssoProvider", label: "SSO Provider", value: "Not configured" },
    ],
    title: "Integrations",
  },
];
