"""
Regenerates app/db/sql_security.py and app/db/sql_bu.py from a pg_dump
schema-only file (default: app/db/service_plus_service.sql).

The source file is a `pg_dump --schema-only` dump containing two Postgres
schemas: a fixed `security` schema and one "template" BU schema (default
name: demo1) whose structure stands in for "a BU schema" in general. Every
object in the dump is preceded by a marker comment of the form:

    --
    -- Name: <object>; Type: <TABLE|SEQUENCE|CONSTRAINT|...>; Schema: <schema>; Owner: <owner>
    --

This script scans for those markers, keeps only the blocks belonging to the
target schema for each pass, strips pg_dump ownership/comment noise, and
(for the BU pass only) strips the schema-qualifier prefix so the emitted DDL
relies on `search_path` like the rest of the BU-schema tooling.

Run manually whenever service_plus_service.sql changes:

    python -m app.db.tools.extract_schema
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

# Matches the 3-line pg_dump object header, e.g.:
#   --
#   -- Name: branch; Type: TABLE; Schema: demo1; Owner: webadmin
#   --
_HEADER_RE = re.compile(
    r"^--\n"
    r"-- Name: (?P<name>.*?); Type: (?P<type>.*?); Schema: (?P<schema>.*?); Owner: (?P<owner>.*?)\n"
    r"--\n",
    re.MULTILINE,
)

# Ownership statements pg_dump appends after most objects; irrelevant to schema
# structure and never present in the hand-maintained files being replaced.
_OWNER_LINE_RE = re.compile(r"^ALTER (?:TABLE|FUNCTION|SEQUENCE) .*\bOWNER TO\b.*;[ \t]*$", re.MULTILINE)

# psql meta-commands emitted by newer pg_dump versions; not valid SQL.
_PSQL_META_RE = re.compile(r"^\\(?:un)?restrict .*$\n?", re.MULTILINE)

# Trailing pg_dump footer. Must be stripped before block-splitting, since the
# last header block in the file runs to EOF and would otherwise swallow it.
_TRAILING_FOOTER_RE = re.compile(r"\n--\n-- PostgreSQL database dump complete\n--\n\s*\Z")

# Object types that carry no schema-structural meaning and are dropped.
# SCHEMA blocks are also implicitly excluded by the schema-name filter (their
# own Schema field is "-"), but listing it here documents the intent.
_SKIP_TYPES = {"SCHEMA", "COMMENT"}

_GENERATED_HEADER = (
    "# AUTO-GENERATED by app/db/tools/extract_schema.py from {source_name}\n"
    "# Do not hand-edit; re-run the extractor instead.\n\n"
)


@dataclass
class DdlBlock:
    name: str
    type_: str
    schema: str
    sql: str


def parse_blocks(source_text: str) -> list[DdlBlock]:
    """Split a pg_dump schema-only file into (name, type, schema, sql) blocks."""
    headers = list(_HEADER_RE.finditer(source_text))
    blocks: list[DdlBlock] = []
    for i, match in enumerate(headers):
        start = match.end()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(source_text)
        blocks.append(
            DdlBlock(
                name=match.group("name"),
                type_=match.group("type"),
                schema=match.group("schema"),
                sql=source_text[start:end],
            )
        )
    return blocks


def _clean_sql(sql: str) -> str:
    sql = _OWNER_LINE_RE.sub("", sql)
    sql = re.sub(r"\n{3,}", "\n\n", sql)
    return sql.strip()


def _strip_schema_qualifier(sql: str, schema_name: str) -> str:
    return re.sub(rf"\b{re.escape(schema_name)}\.", "", sql)


def extract_schema_ddl(blocks: list[DdlBlock], schema_name: str, *, unqualify: bool) -> str:
    """Assemble the DDL for one schema, in source order, as a single string."""
    statements: list[str] = []
    for block in blocks:
        if block.schema != schema_name or block.type_ in _SKIP_TYPES:
            continue
        cleaned = _clean_sql(block.sql)
        if not cleaned:
            continue
        if unqualify:
            cleaned = _strip_schema_qualifier(cleaned, schema_name)
        statements.append(cleaned)
    if not statements:
        raise ValueError(f"No DDL blocks found for schema '{schema_name}' — check --source / schema name")
    return "\n\n".join(statements) + "\n"


def render_module(class_name: str, constant_name: str, ddl: str, source_path: Path) -> str:
    indented_lines = [f"        {line}" if line.strip() else "" for line in ddl.splitlines()]
    indented = "\n".join(indented_lines)
    return (
        _GENERATED_HEADER.format(source_name=source_path.name)
        + f"class {class_name}:\n"
        + f'    """DDL generated from {source_path.name}. Do not hand-edit."""\n\n'
        + f'    {constant_name} = """\n{indented}\n    """\n'
    )


def run(source: Path, bu_schema_name: str, out_dir: Path) -> dict[str, int]:
    text = source.read_text()
    text = _PSQL_META_RE.sub("", text)
    text = _TRAILING_FOOTER_RE.sub("\n", text)
    blocks = parse_blocks(text)

    security_ddl = extract_schema_ddl(blocks, "security", unqualify=False)
    bu_ddl = extract_schema_ddl(blocks, bu_schema_name, unqualify=True)

    security_path = out_dir / "sql_security.py"
    bu_path = out_dir / "sql_bu.py"

    security_path.write_text(render_module("SqlSecurity", "SECURITY_SCHEMA_DDL", security_ddl, source))
    bu_path.write_text(render_module("SqlBu", "BU_SCHEMA_DDL", bu_ddl, source))

    return {
        str(security_path): len(security_ddl.splitlines()),
        str(bu_path): len(bu_ddl.splitlines()),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--source",
        default="app/db/service_plus_service.sql",
        help="Path to the pg_dump schema-only source file.",
    )
    parser.add_argument(
        "--bu-schema-name",
        default="demo1",
        help="Name of the schema in the dump to treat as the BU template.",
    )
    parser.add_argument(
        "--out-dir",
        default="app/db",
        help="Directory to write sql_security.py / sql_bu.py into.",
    )
    args = parser.parse_args()

    written = run(Path(args.source), args.bu_schema_name, Path(args.out_dir))
    for path, line_count in written.items():
        print(f"Wrote {path} ({line_count} lines)")


if __name__ == "__main__":
    main()
