/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@node150483-trace-link.cloudjiffy.net:11085/service_plus_demo -t access_right -t bu -t role -t role_access_right -t user -t user_bu_role -s security
 *
 */


export type Json = unknown;

// Table access_right
export interface AccessRight {
  id: number;
  code: string;
  name: string;
  module: string;
  description: string | null;
  created_at: Date;
  updated_at: Date;
}
export interface AccessRightInput {
  id: number;
  code: string;
  name: string;
  module: string;
  description?: string | null;
  created_at?: Date;
  updated_at?: Date;
}
const access_right = {
  tableName: 'access_right',
  columns: ['id', 'code', 'name', 'module', 'description', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name', 'module'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as AccessRight,
  $input: null as unknown as AccessRightInput
} as const;

// Table bu
export interface Bu {
  id: number;
  code: string;
  name: string;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface BuInput {
  id: number;
  code: string;
  name: string;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const bu = {
  tableName: 'bu',
  columns: ['id', 'code', 'name', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Bu,
  $input: null as unknown as BuInput
} as const;

// Table role
export interface Role {
  id: number;
  code: string;
  name: string;
  description: string | null;
  is_system: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface RoleInput {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  is_system?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const role = {
  tableName: 'role',
  columns: ['id', 'code', 'name', 'description', 'is_system', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Role,
  $input: null as unknown as RoleInput
} as const;

// Table role_access_right
export interface RoleAccessRight {
  role_id: number;
  access_right_id: number;
}
export interface RoleAccessRightInput {
  role_id: number;
  access_right_id: number;
}
const role_access_right = {
  tableName: 'role_access_right',
  columns: ['role_id', 'access_right_id'],
  requiredForInsert: ['role_id', 'access_right_id'],
  primaryKey: 'role_id',
  foreignKeys: {
    role_id: { table: 'role', column: 'id', $type: null as unknown as Role },
    access_right_id: { table: 'access_right', column: 'id', $type: null as unknown as AccessRight },
  },
  $type: null as unknown as RoleAccessRight,
  $input: null as unknown as RoleAccessRightInput
} as const;

// Table user
export interface User {
  id: number;
  username: string;
  email: string;
  mobile: string | null;
  password_hash: string;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
  full_name: string;
  is_admin: boolean;
}
export interface UserInput {
  id: number;
  username: string;
  email: string;
  mobile?: string | null;
  password_hash: string;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
  full_name: string;
  is_admin?: boolean;
}
const user = {
  tableName: 'user',
  columns: ['id', 'username', 'email', 'mobile', 'password_hash', 'is_active', 'created_at', 'updated_at', 'full_name', 'is_admin'],
  requiredForInsert: ['id', 'username', 'email', 'password_hash', 'full_name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as User,
  $input: null as unknown as UserInput
} as const;

// Table user_bu_role
export interface UserBuRole {
  user_id: number;
  bu_id: number;
  role_id: number;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface UserBuRoleInput {
  user_id: number;
  bu_id: number;
  role_id: number;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const user_bu_role = {
  tableName: 'user_bu_role',
  columns: ['user_id', 'bu_id', 'role_id', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['user_id', 'bu_id', 'role_id'],
  primaryKey: 'user_id',
  foreignKeys: {
    user_id: { table: 'user', column: 'id', $type: null as unknown as User },
    bu_id: { table: 'bu', column: 'id', $type: null as unknown as Bu },
    role_id: { table: 'role', column: 'id', $type: null as unknown as Role },
  },
  $type: null as unknown as UserBuRole,
  $input: null as unknown as UserBuRoleInput
} as const;


export interface TableTypes {
  access_right: {
    select: AccessRight;
    input: AccessRightInput;
  };
  bu: {
    select: Bu;
    input: BuInput;
  };
  role: {
    select: Role;
    input: RoleInput;
  };
  role_access_right: {
    select: RoleAccessRight;
    input: RoleAccessRightInput;
  };
  user: {
    select: User;
    input: UserInput;
  };
  user_bu_role: {
    select: UserBuRole;
    input: UserBuRoleInput;
  };
}

export const tables = {
  access_right,
  bu,
  role,
  role_access_right,
  user,
  user_bu_role,
}
