/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@node150483-trace-link.cloudjiffy.net:11085/service_plus_demo -t app_setting -t branch -t brand -t company_info -t customer_contact -t customer_type -t document_sequence -t document_type -t financial_year -t job -t job_additional_charge -t job_delivery_manner -t job_invoice -t job_invoice_line -t job_part_used -t job_payment -t job_receive_condition -t job_receive_manner -t job_status -t job_transaction -t job_type -t product -t product_brand_model -t purchase_invoice -t purchase_invoice_line -t sales_invoice -t sales_invoice_line -t spare_part_master -t state -t stock_adjustment -t stock_adjustment_line -t stock_transaction -t stock_transaction_type -t supplier -t technician -s demo1
 *
 */


export type Json = unknown;

// Table app_setting
export interface AppSetting {
  id: number;
  setting_key: string;
  setting_type: string;
  setting_value: Json;
  description: string | null;
  is_editable: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface AppSettingInput {
  id: number;
  setting_key: string;
  setting_type: string;
  setting_value: Json;
  description?: string | null;
  is_editable?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const app_setting = {
  tableName: 'app_setting',
  columns: ['id', 'setting_key', 'setting_type', 'setting_value', 'description', 'is_editable', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'setting_key', 'setting_type', 'setting_value'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as AppSetting,
  $input: null as unknown as AppSettingInput
} as const;

// Table branch
export interface Branch {
  id: number;
  bu_id: number;
  code: string;
  name: string;
  phone: string | null;
  email: string | null;
  address_line1: string;
  address_line2: string | null;
  state_id: number;
  city: string | null;
  pincode: string;
  gstin: string | null;
  is_active: boolean;
  is_head_office: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface BranchInput {
  id: number;
  bu_id: number;
  code: string;
  name: string;
  phone?: string | null;
  email?: string | null;
  address_line1: string;
  address_line2?: string | null;
  state_id: number;
  city?: string | null;
  pincode: string;
  gstin?: string | null;
  is_active?: boolean;
  is_head_office?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const branch = {
  tableName: 'branch',
  columns: ['id', 'bu_id', 'code', 'name', 'phone', 'email', 'address_line1', 'address_line2', 'state_id', 'city', 'pincode', 'gstin', 'is_active', 'is_head_office', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'bu_id', 'code', 'name', 'address_line1', 'state_id', 'pincode'],
  primaryKey: 'id',
  foreignKeys: { state_id: { table: 'state', column: 'id', $type: null as unknown as State }, },
  $type: null as unknown as Branch,
  $input: null as unknown as BranchInput
} as const;

// Table brand
export interface Brand {
  id: number;
  code: string;
  name: string;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface BrandInput {
  id: number;
  code: string;
  name: string;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const brand = {
  tableName: 'brand',
  columns: ['id', 'code', 'name', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Brand,
  $input: null as unknown as BrandInput
} as const;

// Table company_info
export interface CompanyInfo {
  id: number;
  company_name: string;
  address_line1: string;
  address_line2: string | null;
  city: string | null;
  state_id: number;
  country: string | null;
  pincode: string | null;
  phone: string | null;
  email: string | null;
  gstin: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface CompanyInfoInput {
  id: number;
  company_name: string;
  address_line1: string;
  address_line2?: string | null;
  city?: string | null;
  state_id: number;
  country?: string | null;
  pincode?: string | null;
  phone?: string | null;
  email?: string | null;
  gstin?: string | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const company_info = {
  tableName: 'company_info',
  columns: ['id', 'company_name', 'address_line1', 'address_line2', 'city', 'state_id', 'country', 'pincode', 'phone', 'email', 'gstin', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'company_name', 'address_line1', 'state_id'],
  primaryKey: 'id',
  foreignKeys: { state_id: { table: 'state', column: 'id', $type: null as unknown as State }, },
  $type: null as unknown as CompanyInfo,
  $input: null as unknown as CompanyInfoInput
} as const;

// Table customer_contact
export interface CustomerContact {
  id: number;
  customer_type_id: number;
  full_name: string | null;
  gstin: string | null;
  mobile: string;
  alternate_mobile: string | null;
  email: string | null;
  address_line1: string;
  address_line2: string | null;
  landmark: string | null;
  state_id: number;
  city: string | null;
  postal_code: string | null;
  remarks: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface CustomerContactInput {
  id: number;
  customer_type_id: number;
  full_name?: string | null;
  gstin?: string | null;
  mobile: string;
  alternate_mobile?: string | null;
  email?: string | null;
  address_line1: string;
  address_line2?: string | null;
  landmark?: string | null;
  state_id: number;
  city?: string | null;
  postal_code?: string | null;
  remarks?: string | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const customer_contact = {
  tableName: 'customer_contact',
  columns: ['id', 'customer_type_id', 'full_name', 'gstin', 'mobile', 'alternate_mobile', 'email', 'address_line1', 'address_line2', 'landmark', 'state_id', 'city', 'postal_code', 'remarks', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'customer_type_id', 'mobile', 'address_line1', 'state_id'],
  primaryKey: 'id',
  foreignKeys: {
    customer_type_id: { table: 'customer_type', column: 'id', $type: null as unknown as CustomerType },
    state_id: { table: 'state', column: 'id', $type: null as unknown as State },
  },
  $type: null as unknown as CustomerContact,
  $input: null as unknown as CustomerContactInput
} as const;

// Table customer_type
export interface CustomerType {
  id: number;
  code: string;
  name: string;
  description: string | null;
  is_active: boolean;
  display_order: number | null;
}
export interface CustomerTypeInput {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  is_active?: boolean;
  display_order?: number | null;
}
const customer_type = {
  tableName: 'customer_type',
  columns: ['id', 'code', 'name', 'description', 'is_active', 'display_order'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as CustomerType,
  $input: null as unknown as CustomerTypeInput
} as const;

// Table document_sequence
export interface DocumentSequence {
  id: number;
  document_type_id: number;
  branch_id: number;
  prefix: string;
  next_number: number;
  padding: number;
  separator: string;
  created_at: Date;
  updated_at: Date;
}
export interface DocumentSequenceInput {
  id: number;
  document_type_id: number;
  branch_id: number;
  prefix: string;
  next_number?: number;
  padding?: number;
  separator?: string;
  created_at?: Date;
  updated_at?: Date;
}
const document_sequence = {
  tableName: 'document_sequence',
  columns: ['id', 'document_type_id', 'branch_id', 'prefix', 'next_number', 'padding', 'separator', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'document_type_id', 'branch_id', 'prefix'],
  primaryKey: 'id',
  foreignKeys: {
    document_type_id: { table: 'document_type', column: 'id', $type: null as unknown as DocumentType },
    branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch },
  },
  $type: null as unknown as DocumentSequence,
  $input: null as unknown as DocumentSequenceInput
} as const;

// Table document_type
export interface DocumentType {
  id: number;
  code: string;
  prefix: string;
  name: string;
  description: string | null;
}
export interface DocumentTypeInput {
  id: number;
  code: string;
  prefix: string;
  name: string;
  description?: string | null;
}
const document_type = {
  tableName: 'document_type',
  columns: ['id', 'code', 'prefix', 'name', 'description'],
  requiredForInsert: ['id', 'code', 'prefix', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as DocumentType,
  $input: null as unknown as DocumentTypeInput
} as const;

// Table financial_year
export interface FinancialYear {
  id: number;
  start_date: Date;
  end_date: Date;
}
export interface FinancialYearInput {
  id: number;
  start_date: Date;
  end_date: Date;
}
const financial_year = {
  tableName: 'financial_year',
  columns: ['id', 'start_date', 'end_date'],
  requiredForInsert: ['id', 'start_date', 'end_date'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as FinancialYear,
  $input: null as unknown as FinancialYearInput
} as const;

// Table job
export interface Job {
  id: number;
  job_no: string;
  job_date: Date;
  customer_contact_id: number;
  branch_id: number;
  technician_id: number | null;
  job_status_id: number;
  job_type_id: number;
  job_receive_manner_id: number;
  job_receive_condition_id: number | null;
  product_brand_model_id: number | null;
  serial_no: string | null;
  problem_reported: string;
  diagnosis: string | null;
  work_done: string | null;
  remarks: string | null;
  amount: number | null;
  delivery_date: Date | null;
  is_closed: boolean;
  is_warranty: boolean;
  warranty_card_no: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
  address_snapshot: string | null;
  last_transaction_id: number | null;
  is_final: boolean;
}
export interface JobInput {
  id: number;
  job_no: string;
  job_date?: Date;
  customer_contact_id: number;
  branch_id: number;
  technician_id?: number | null;
  job_status_id: number;
  job_type_id: number;
  job_receive_manner_id: number;
  job_receive_condition_id?: number | null;
  product_brand_model_id?: number | null;
  serial_no?: string | null;
  problem_reported: string;
  diagnosis?: string | null;
  work_done?: string | null;
  remarks?: string | null;
  amount?: number | null;
  delivery_date?: Date | null;
  is_closed?: boolean;
  is_warranty?: boolean;
  warranty_card_no?: string | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
  address_snapshot?: string | null;
  last_transaction_id?: number | null;
  is_final?: boolean;
}
const job = {
  tableName: 'job',
  columns: ['id', 'job_no', 'job_date', 'customer_contact_id', 'branch_id', 'technician_id', 'job_status_id', 'job_type_id', 'job_receive_manner_id', 'job_receive_condition_id', 'product_brand_model_id', 'serial_no', 'problem_reported', 'diagnosis', 'work_done', 'remarks', 'amount', 'delivery_date', 'is_closed', 'is_warranty', 'warranty_card_no', 'is_active', 'created_at', 'updated_at', 'address_snapshot', 'last_transaction_id', 'is_final'],
  requiredForInsert: ['id', 'job_no', 'customer_contact_id', 'branch_id', 'job_status_id', 'job_type_id', 'job_receive_manner_id', 'problem_reported'],
  primaryKey: 'id',
  foreignKeys: {
    customer_contact_id: { table: 'customer_contact', column: 'id', $type: null as unknown as CustomerContact },
    branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch },
    technician_id: { table: 'technician', column: 'id', $type: null as unknown as Technician },
    job_status_id: { table: 'job_status', column: 'id', $type: null as unknown as JobStatus },
    job_type_id: { table: 'job_type', column: 'id', $type: null as unknown as JobType },
    job_receive_manner_id: { table: 'job_receive_manner', column: 'id', $type: null as unknown as JobReceiveManner },
    job_receive_condition_id: { table: 'job_receive_condition', column: 'id', $type: null as unknown as JobReceiveCondition },
    product_brand_model_id: { table: 'product_brand_model', column: 'id', $type: null as unknown as ProductBrandModel },
  },
  $type: null as unknown as Job,
  $input: null as unknown as JobInput
} as const;

// Table job_additional_charge
export interface JobAdditionalCharge {
  id: number;
  job_id: number;
  charge_name: string;
  ref_no: string | null;
  description: string | null;
  cost_price: number;
  selling_price: number;
  created_at: Date;
}
export interface JobAdditionalChargeInput {
  id: number;
  job_id: number;
  charge_name: string;
  ref_no?: string | null;
  description?: string | null;
  cost_price?: number;
  selling_price?: number;
  created_at?: Date;
}
const job_additional_charge = {
  tableName: 'job_additional_charge',
  columns: ['id', 'job_id', 'charge_name', 'ref_no', 'description', 'cost_price', 'selling_price', 'created_at'],
  requiredForInsert: ['id', 'job_id', 'charge_name'],
  primaryKey: 'id',
  foreignKeys: { job_id: { table: 'job', column: 'id', $type: null as unknown as Job }, },
  $type: null as unknown as JobAdditionalCharge,
  $input: null as unknown as JobAdditionalChargeInput
} as const;

// Table job_delivery_manner
export interface JobDeliveryManner {
  id: number;
  code: string;
  name: string;
  display_order: number | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface JobDeliveryMannerInput {
  id: number;
  code: string;
  name: string;
  display_order?: number | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const job_delivery_manner = {
  tableName: 'job_delivery_manner',
  columns: ['id', 'code', 'name', 'display_order', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as JobDeliveryManner,
  $input: null as unknown as JobDeliveryMannerInput
} as const;

// Table job_invoice
export interface JobInvoice {
  id: number;
  job_id: number;
  company_id: number;
  invoice_no: string;
  invoice_date: Date;
  supply_state_code: string;
  taxable_amount: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  total_tax: number;
  total_amount: number;
  created_at: Date;
  updated_at: Date;
}
export interface JobInvoiceInput {
  id: number;
  job_id: number;
  company_id: number;
  invoice_no: string;
  invoice_date?: Date;
  supply_state_code: string;
  taxable_amount: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  total_tax: number;
  total_amount: number;
  created_at?: Date;
  updated_at?: Date;
}
const job_invoice = {
  tableName: 'job_invoice',
  columns: ['id', 'job_id', 'company_id', 'invoice_no', 'invoice_date', 'supply_state_code', 'taxable_amount', 'cgst_amount', 'sgst_amount', 'igst_amount', 'total_tax', 'total_amount', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'job_id', 'company_id', 'invoice_no', 'supply_state_code', 'taxable_amount', 'total_tax', 'total_amount'],
  primaryKey: 'id',
  foreignKeys: {
    job_id: { table: 'job', column: 'id', $type: null as unknown as Job },
    company_id: { table: 'company_info', column: 'id', $type: null as unknown as CompanyInfo },
  },
  $type: null as unknown as JobInvoice,
  $input: null as unknown as JobInvoiceInput
} as const;

// Table job_invoice_line
export interface JobInvoiceLine {
  id: number;
  job_invoice_id: number;
  description: string;
  part_code: string | null;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  taxable_amount: number;
  cgst_rate: number;
  sgst_rate: number;
  igst_rate: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  total_amount: number;
  created_at: Date;
  updated_at: Date;
}
export interface JobInvoiceLineInput {
  id: number;
  job_invoice_id: number;
  description: string;
  part_code?: string | null;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  taxable_amount: number;
  cgst_rate?: number;
  sgst_rate?: number;
  igst_rate?: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  total_amount: number;
  created_at?: Date;
  updated_at?: Date;
}
const job_invoice_line = {
  tableName: 'job_invoice_line',
  columns: ['id', 'job_invoice_id', 'description', 'part_code', 'hsn_code', 'quantity', 'unit_price', 'taxable_amount', 'cgst_rate', 'sgst_rate', 'igst_rate', 'cgst_amount', 'sgst_amount', 'igst_amount', 'total_amount', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'job_invoice_id', 'description', 'hsn_code', 'quantity', 'unit_price', 'taxable_amount', 'total_amount'],
  primaryKey: 'id',
  foreignKeys: { job_invoice_id: { table: 'job_invoice', column: 'id', $type: null as unknown as JobInvoice }, },
  $type: null as unknown as JobInvoiceLine,
  $input: null as unknown as JobInvoiceLineInput
} as const;

// Table job_part_used
export interface JobPartUsed {
  id: number;
  job_id: number;
  part_id: number;
  quantity: number;
  created_at: Date;
  updated_at: Date;
}
export interface JobPartUsedInput {
  id: number;
  job_id: number;
  part_id: number;
  quantity: number;
  created_at?: Date;
  updated_at?: Date;
}
const job_part_used = {
  tableName: 'job_part_used',
  columns: ['id', 'job_id', 'part_id', 'quantity', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'job_id', 'part_id', 'quantity'],
  primaryKey: 'id',
  foreignKeys: {
    job_id: { table: 'job', column: 'id', $type: null as unknown as Job },
    part_id: { table: 'spare_part_master', column: 'id', $type: null as unknown as SparePartMaster },
  },
  $type: null as unknown as JobPartUsed,
  $input: null as unknown as JobPartUsedInput
} as const;

// Table job_payment
export interface JobPayment {
  id: number;
  job_id: number;
  payment_date: Date;
  payment_mode: string;
  amount: number;
  reference_no: string | null;
  remarks: string | null;
  created_at: Date;
  updated_at: Date;
}
export interface JobPaymentInput {
  id: number;
  job_id: number;
  payment_date: Date;
  payment_mode: string;
  amount: number;
  reference_no?: string | null;
  remarks?: string | null;
  created_at?: Date;
  updated_at?: Date;
}
const job_payment = {
  tableName: 'job_payment',
  columns: ['id', 'job_id', 'payment_date', 'payment_mode', 'amount', 'reference_no', 'remarks', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'job_id', 'payment_date', 'payment_mode', 'amount'],
  primaryKey: 'id',
  foreignKeys: { job_id: { table: 'job', column: 'id', $type: null as unknown as Job }, },
  $type: null as unknown as JobPayment,
  $input: null as unknown as JobPaymentInput
} as const;

// Table job_receive_condition
export interface JobReceiveCondition {
  id: number;
  code: string;
  name: string;
  description: string | null;
  display_order: number | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface JobReceiveConditionInput {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  display_order?: number | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const job_receive_condition = {
  tableName: 'job_receive_condition',
  columns: ['id', 'code', 'name', 'description', 'display_order', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as JobReceiveCondition,
  $input: null as unknown as JobReceiveConditionInput
} as const;

// Table job_receive_manner
export interface JobReceiveManner {
  id: number;
  code: string;
  name: string;
  is_system: boolean;
  is_active: boolean;
  display_order: number;
  created_at: Date;
  updated_at: Date;
}
export interface JobReceiveMannerInput {
  id: number;
  code: string;
  name: string;
  is_system?: boolean;
  is_active?: boolean;
  display_order?: number;
  created_at?: Date;
  updated_at?: Date;
}
const job_receive_manner = {
  tableName: 'job_receive_manner',
  columns: ['id', 'code', 'name', 'is_system', 'is_active', 'display_order', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as JobReceiveManner,
  $input: null as unknown as JobReceiveMannerInput
} as const;

// Table job_status
export interface JobStatus {
  id: number;
  code: string;
  name: string;
  description: string | null;
  display_order: number;
  is_initial: boolean;
  is_final: boolean;
  is_active: boolean;
  is_system: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface JobStatusInput {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  display_order: number;
  is_initial?: boolean;
  is_final?: boolean;
  is_active?: boolean;
  is_system?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const job_status = {
  tableName: 'job_status',
  columns: ['id', 'code', 'name', 'description', 'display_order', 'is_initial', 'is_final', 'is_active', 'is_system', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name', 'display_order'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as JobStatus,
  $input: null as unknown as JobStatusInput
} as const;

// Table job_transaction
export interface JobTransaction {
  id: number;
  job_id: number;
  status_id: number | null;
  technician_id: number | null;
  amount: number | null;
  notes: string | null;
  performed_by_user_id: number;
  performed_at: Date;
  previous_transaction_id: number | null;
}
export interface JobTransactionInput {
  id: number;
  job_id: number;
  status_id?: number | null;
  technician_id?: number | null;
  amount?: number | null;
  notes?: string | null;
  performed_by_user_id: number;
  performed_at?: Date;
  previous_transaction_id?: number | null;
}
const job_transaction = {
  tableName: 'job_transaction',
  columns: ['id', 'job_id', 'status_id', 'technician_id', 'amount', 'notes', 'performed_by_user_id', 'performed_at', 'previous_transaction_id'],
  requiredForInsert: ['id', 'job_id', 'performed_by_user_id'],
  primaryKey: 'id',
  foreignKeys: {
    job_id: { table: 'job', column: 'id', $type: null as unknown as Job },
    status_id: { table: 'job_status', column: 'id', $type: null as unknown as JobStatus },
    technician_id: { table: 'technician', column: 'id', $type: null as unknown as Technician },
  },
  $type: null as unknown as JobTransaction,
  $input: null as unknown as JobTransactionInput
} as const;

// Table job_type
export interface JobType {
  id: number;
  code: string;
  name: string;
  description: string | null;
  display_order: number | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface JobTypeInput {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  display_order?: number | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const job_type = {
  tableName: 'job_type',
  columns: ['id', 'code', 'name', 'description', 'display_order', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as JobType,
  $input: null as unknown as JobTypeInput
} as const;

// Table product
export interface Product {
  id: number;
  name: string;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface ProductInput {
  id: number;
  name: string;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const product = {
  tableName: 'product',
  columns: ['id', 'name', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Product,
  $input: null as unknown as ProductInput
} as const;

// Table product_brand_model
export interface ProductBrandModel {
  id: number;
  product_id: number;
  brand_id: number;
  model_name: string;
  launch_year: number | null;
  remarks: string | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface ProductBrandModelInput {
  id: number;
  product_id: number;
  brand_id: number;
  model_name: string;
  launch_year?: number | null;
  remarks?: string | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const product_brand_model = {
  tableName: 'product_brand_model',
  columns: ['id', 'product_id', 'brand_id', 'model_name', 'launch_year', 'remarks', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'product_id', 'brand_id', 'model_name'],
  primaryKey: 'id',
  foreignKeys: {
    product_id: { table: 'product', column: 'id', $type: null as unknown as Product },
    brand_id: { table: 'brand', column: 'id', $type: null as unknown as Brand },
  },
  $type: null as unknown as ProductBrandModel,
  $input: null as unknown as ProductBrandModelInput
} as const;

// Table purchase_invoice
export interface PurchaseInvoice {
  id: number;
  supplier_id: number;
  invoice_no: string;
  invoice_date: Date;
  supplier_state_code: string;
  taxable_amount: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  total_tax: number;
  total_amount: number;
  branch_id: number;
  remarks: string | null;
  created_at: Date;
  updated_at: Date;
}
export interface PurchaseInvoiceInput {
  id: number;
  supplier_id: number;
  invoice_no: string;
  invoice_date: Date;
  supplier_state_code: string;
  taxable_amount: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  total_tax: number;
  total_amount: number;
  branch_id: number;
  remarks?: string | null;
  created_at?: Date;
  updated_at?: Date;
}
const purchase_invoice = {
  tableName: 'purchase_invoice',
  columns: ['id', 'supplier_id', 'invoice_no', 'invoice_date', 'supplier_state_code', 'taxable_amount', 'cgst_amount', 'sgst_amount', 'igst_amount', 'total_tax', 'total_amount', 'branch_id', 'remarks', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'supplier_id', 'invoice_no', 'invoice_date', 'supplier_state_code', 'taxable_amount', 'total_tax', 'total_amount', 'branch_id'],
  primaryKey: 'id',
  foreignKeys: {
    supplier_id: { table: 'supplier', column: 'id', $type: null as unknown as Supplier },
    branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch },
  },
  $type: null as unknown as PurchaseInvoice,
  $input: null as unknown as PurchaseInvoiceInput
} as const;

// Table purchase_invoice_line
export interface PurchaseInvoiceLine {
  id: number;
  purchase_invoice_id: number;
  part_id: number;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  taxable_amount: number;
  cgst_rate: number;
  sgst_rate: number;
  igst_rate: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  total_amount: number;
  created_at: Date;
  updated_at: Date;
}
export interface PurchaseInvoiceLineInput {
  id: number;
  purchase_invoice_id: number;
  part_id: number;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  taxable_amount: number;
  cgst_rate?: number;
  sgst_rate?: number;
  igst_rate?: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  total_amount: number;
  created_at?: Date;
  updated_at?: Date;
}
const purchase_invoice_line = {
  tableName: 'purchase_invoice_line',
  columns: ['id', 'purchase_invoice_id', 'part_id', 'hsn_code', 'quantity', 'unit_price', 'taxable_amount', 'cgst_rate', 'sgst_rate', 'igst_rate', 'cgst_amount', 'sgst_amount', 'igst_amount', 'total_amount', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'purchase_invoice_id', 'part_id', 'hsn_code', 'quantity', 'unit_price', 'taxable_amount', 'total_amount'],
  primaryKey: 'id',
  foreignKeys: {
    purchase_invoice_id: { table: 'purchase_invoice', column: 'id', $type: null as unknown as PurchaseInvoice },
    part_id: { table: 'spare_part_master', column: 'id', $type: null as unknown as SparePartMaster },
  },
  $type: null as unknown as PurchaseInvoiceLine,
  $input: null as unknown as PurchaseInvoiceLineInput
} as const;

// Table sales_invoice
export interface SalesInvoice {
  id: number;
  invoice_no: string;
  invoice_date: Date;
  company_id: number;
  customer_contact_id: number | null;
  customer_name: string;
  customer_gstin: string | null;
  customer_state_code: string;
  taxable_amount: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  total_tax: number;
  total_amount: number;
  branch_id: number;
  remarks: string | null;
  created_at: Date;
  updated_at: Date;
}
export interface SalesInvoiceInput {
  id: number;
  invoice_no: string;
  invoice_date: Date;
  company_id: number;
  customer_contact_id?: number | null;
  customer_name: string;
  customer_gstin?: string | null;
  customer_state_code: string;
  taxable_amount: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  total_tax: number;
  total_amount: number;
  branch_id: number;
  remarks?: string | null;
  created_at?: Date;
  updated_at?: Date;
}
const sales_invoice = {
  tableName: 'sales_invoice',
  columns: ['id', 'invoice_no', 'invoice_date', 'company_id', 'customer_contact_id', 'customer_name', 'customer_gstin', 'customer_state_code', 'taxable_amount', 'cgst_amount', 'sgst_amount', 'igst_amount', 'total_tax', 'total_amount', 'branch_id', 'remarks', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'invoice_no', 'invoice_date', 'company_id', 'customer_name', 'customer_state_code', 'taxable_amount', 'total_tax', 'total_amount', 'branch_id'],
  primaryKey: 'id',
  foreignKeys: {
    company_id: { table: 'company_info', column: 'id', $type: null as unknown as CompanyInfo },
    customer_contact_id: { table: 'customer_contact', column: 'id', $type: null as unknown as CustomerContact },
    branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch },
  },
  $type: null as unknown as SalesInvoice,
  $input: null as unknown as SalesInvoiceInput
} as const;

// Table sales_invoice_line
export interface SalesInvoiceLine {
  id: number;
  sales_invoice_id: number;
  part_id: number;
  item_description: string;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  gst_rate: number;
  taxable_amount: number;
  cgst_amount: number;
  sgst_amount: number;
  igst_amount: number;
  total_amount: number;
  created_at: Date;
  updated_at: Date;
}
export interface SalesInvoiceLineInput {
  id: number;
  sales_invoice_id: number;
  part_id: number;
  item_description: string;
  hsn_code: string;
  quantity: number;
  unit_price: number;
  gst_rate?: number;
  taxable_amount: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  total_amount: number;
  created_at?: Date;
  updated_at?: Date;
}
const sales_invoice_line = {
  tableName: 'sales_invoice_line',
  columns: ['id', 'sales_invoice_id', 'part_id', 'item_description', 'hsn_code', 'quantity', 'unit_price', 'gst_rate', 'taxable_amount', 'cgst_amount', 'sgst_amount', 'igst_amount', 'total_amount', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'sales_invoice_id', 'part_id', 'item_description', 'hsn_code', 'quantity', 'unit_price', 'taxable_amount', 'total_amount'],
  primaryKey: 'id',
  foreignKeys: {
    sales_invoice_id: { table: 'sales_invoice', column: 'id', $type: null as unknown as SalesInvoice },
    part_id: { table: 'spare_part_master', column: 'id', $type: null as unknown as SparePartMaster },
  },
  $type: null as unknown as SalesInvoiceLine,
  $input: null as unknown as SalesInvoiceLineInput
} as const;

// Table spare_part_master
export interface SparePartMaster {
  id: number;
  brand_id: number;
  part_code: string;
  part_name: string;
  part_description: string | null;
  category: string | null;
  model: string | null;
  uom: string;
  cost_price: number | null;
  mrp: number | null;
  hsn_code: string | null;
  gst_rate: number | null;
  is_active: boolean;
  created_at: Date | null;
  updated_at: Date | null;
}
export interface SparePartMasterInput {
  id: number;
  brand_id: number;
  part_code: string;
  part_name: string;
  part_description?: string | null;
  category?: string | null;
  model?: string | null;
  uom?: string;
  cost_price?: number | null;
  mrp?: number | null;
  hsn_code?: string | null;
  gst_rate?: number | null;
  is_active?: boolean;
  created_at?: Date | null;
  updated_at?: Date | null;
}
const spare_part_master = {
  tableName: 'spare_part_master',
  columns: ['id', 'brand_id', 'part_code', 'part_name', 'part_description', 'category', 'model', 'uom', 'cost_price', 'mrp', 'hsn_code', 'gst_rate', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'brand_id', 'part_code', 'part_name'],
  primaryKey: 'id',
  foreignKeys: { brand_id: { table: 'brand', column: 'id', $type: null as unknown as Brand }, },
  $type: null as unknown as SparePartMaster,
  $input: null as unknown as SparePartMasterInput
} as const;

// Table state
export interface State {
  id: number;
  code: string;
  name: string;
  country_code: string;
  gst_state_code: string | null;
  is_union_territory: boolean;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface StateInput {
  id: number;
  code: string;
  name: string;
  country_code?: string;
  gst_state_code?: string | null;
  is_union_territory?: boolean;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const state = {
  tableName: 'state',
  columns: ['id', 'code', 'name', 'country_code', 'gst_state_code', 'is_union_territory', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as State,
  $input: null as unknown as StateInput
} as const;

// Table stock_adjustment
export interface StockAdjustment {
  id: number;
  adjustment_date: Date;
  adjustment_reason: string;
  ref_no: string | null;
  branch_id: number;
  remarks: string | null;
  /** Loosely coupled to user table - no FK constraint */
  created_by: number | null;
  created_at: Date;
  updated_at: Date;
}
export interface StockAdjustmentInput {
  id: number;
  adjustment_date: Date;
  adjustment_reason: string;
  ref_no?: string | null;
  branch_id: number;
  remarks?: string | null;
  /** Loosely coupled to user table - no FK constraint */
  created_by?: number | null;
  created_at?: Date;
  updated_at?: Date;
}
const stock_adjustment = {
  tableName: 'stock_adjustment',
  columns: ['id', 'adjustment_date', 'adjustment_reason', 'ref_no', 'branch_id', 'remarks', 'created_by', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'adjustment_date', 'adjustment_reason', 'branch_id'],
  primaryKey: 'id',
  foreignKeys: { branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch }, },
  $type: null as unknown as StockAdjustment,
  $input: null as unknown as StockAdjustmentInput
} as const;

// Table stock_adjustment_line
export interface StockAdjustmentLine {
  id: number;
  stock_adjustment_id: number;
  part_id: number;
  dr_cr: string;
  qty: number;
  unit_cost: number | null;
  remarks: string | null;
  created_at: Date;
  updated_at: Date;
}
export interface StockAdjustmentLineInput {
  id: number;
  stock_adjustment_id: number;
  part_id: number;
  dr_cr: string;
  qty: number;
  unit_cost?: number | null;
  remarks?: string | null;
  created_at?: Date;
  updated_at?: Date;
}
const stock_adjustment_line = {
  tableName: 'stock_adjustment_line',
  columns: ['id', 'stock_adjustment_id', 'part_id', 'dr_cr', 'qty', 'unit_cost', 'remarks', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'stock_adjustment_id', 'part_id', 'dr_cr', 'qty'],
  primaryKey: 'id',
  foreignKeys: {
    stock_adjustment_id: { table: 'stock_adjustment', column: 'id', $type: null as unknown as StockAdjustment },
    part_id: { table: 'spare_part_master', column: 'id', $type: null as unknown as SparePartMaster },
  },
  $type: null as unknown as StockAdjustmentLine,
  $input: null as unknown as StockAdjustmentLineInput
} as const;

// Table stock_transaction
export interface StockTransaction {
  id: number;
  part_id: number;
  branch_id: number;
  stock_transaction_type_id: number;
  transaction_date: Date;
  dr_cr: string;
  qty: number;
  unit_cost: number | null;
  remarks: string | null;
  created_at: Date;
  purchase_line_id: number | null;
  sales_line_id: number | null;
  adjustment_line_id: number | null;
  job_part_used_id: number | null;
}
export interface StockTransactionInput {
  id: number;
  part_id: number;
  branch_id: number;
  stock_transaction_type_id: number;
  transaction_date: Date;
  dr_cr: string;
  qty: number;
  unit_cost?: number | null;
  remarks?: string | null;
  created_at?: Date;
  purchase_line_id?: number | null;
  sales_line_id?: number | null;
  adjustment_line_id?: number | null;
  job_part_used_id?: number | null;
}
const stock_transaction = {
  tableName: 'stock_transaction',
  columns: ['id', 'part_id', 'branch_id', 'stock_transaction_type_id', 'transaction_date', 'dr_cr', 'qty', 'unit_cost', 'remarks', 'created_at', 'purchase_line_id', 'sales_line_id', 'adjustment_line_id', 'job_part_used_id'],
  requiredForInsert: ['id', 'part_id', 'branch_id', 'stock_transaction_type_id', 'transaction_date', 'dr_cr', 'qty'],
  primaryKey: 'id',
  foreignKeys: {
    part_id: { table: 'spare_part_master', column: 'id', $type: null as unknown as SparePartMaster },
    branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch },
    stock_transaction_type_id: { table: 'stock_transaction_type', column: 'id', $type: null as unknown as StockTransactionType },
    purchase_line_id: { table: 'purchase_invoice_line', column: 'id', $type: null as unknown as PurchaseInvoiceLine },
    sales_line_id: { table: 'sales_invoice_line', column: 'id', $type: null as unknown as SalesInvoiceLine },
    adjustment_line_id: { table: 'stock_adjustment_line', column: 'id', $type: null as unknown as StockAdjustmentLine },
    job_part_used_id: { table: 'job_part_used', column: 'id', $type: null as unknown as JobPartUsed },
  },
  $type: null as unknown as StockTransaction,
  $input: null as unknown as StockTransactionInput
} as const;

// Table stock_transaction_type
export interface StockTransactionType {
  id: number;
  code: string;
  name: string;
  dr_cr: string;
  description: string | null;
  is_active: boolean;
}
export interface StockTransactionTypeInput {
  id: number;
  code: string;
  name: string;
  dr_cr: string;
  description?: string | null;
  is_active?: boolean;
}
const stock_transaction_type = {
  tableName: 'stock_transaction_type',
  columns: ['id', 'code', 'name', 'dr_cr', 'description', 'is_active'],
  requiredForInsert: ['id', 'code', 'name', 'dr_cr'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as StockTransactionType,
  $input: null as unknown as StockTransactionTypeInput
} as const;

// Table supplier
export interface Supplier {
  id: number;
  name: string;
  gstin: string | null;
  pan: string | null;
  phone: string | null;
  email: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state_id: number;
  pincode: string | null;
  is_active: boolean;
  remarks: string | null;
  created_at: Date;
  updated_at: Date;
}
export interface SupplierInput {
  id: number;
  name: string;
  gstin?: string | null;
  pan?: string | null;
  phone?: string | null;
  email?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state_id: number;
  pincode?: string | null;
  is_active?: boolean;
  remarks?: string | null;
  created_at?: Date;
  updated_at?: Date;
}
const supplier = {
  tableName: 'supplier',
  columns: ['id', 'name', 'gstin', 'pan', 'phone', 'email', 'address_line1', 'address_line2', 'city', 'state_id', 'pincode', 'is_active', 'remarks', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'name', 'state_id'],
  primaryKey: 'id',
  foreignKeys: { state_id: { table: 'state', column: 'id', $type: null as unknown as State }, },
  $type: null as unknown as Supplier,
  $input: null as unknown as SupplierInput
} as const;

// Table technician
export interface Technician {
  id: number;
  branch_id: number;
  code: string;
  name: string;
  phone: string | null;
  email: string | null;
  specialization: string | null;
  leaving_date: Date | null;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface TechnicianInput {
  id: number;
  branch_id: number;
  code: string;
  name: string;
  phone?: string | null;
  email?: string | null;
  specialization?: string | null;
  leaving_date?: Date | null;
  is_active?: boolean;
  created_at?: Date;
  updated_at?: Date;
}
const technician = {
  tableName: 'technician',
  columns: ['id', 'branch_id', 'code', 'name', 'phone', 'email', 'specialization', 'leaving_date', 'is_active', 'created_at', 'updated_at'],
  requiredForInsert: ['id', 'branch_id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: { branch_id: { table: 'branch', column: 'id', $type: null as unknown as Branch }, },
  $type: null as unknown as Technician,
  $input: null as unknown as TechnicianInput
} as const;


export interface TableTypes {
  app_setting: {
    select: AppSetting;
    input: AppSettingInput;
  };
  branch: {
    select: Branch;
    input: BranchInput;
  };
  brand: {
    select: Brand;
    input: BrandInput;
  };
  company_info: {
    select: CompanyInfo;
    input: CompanyInfoInput;
  };
  customer_contact: {
    select: CustomerContact;
    input: CustomerContactInput;
  };
  customer_type: {
    select: CustomerType;
    input: CustomerTypeInput;
  };
  document_sequence: {
    select: DocumentSequence;
    input: DocumentSequenceInput;
  };
  document_type: {
    select: DocumentType;
    input: DocumentTypeInput;
  };
  financial_year: {
    select: FinancialYear;
    input: FinancialYearInput;
  };
  job: {
    select: Job;
    input: JobInput;
  };
  job_additional_charge: {
    select: JobAdditionalCharge;
    input: JobAdditionalChargeInput;
  };
  job_delivery_manner: {
    select: JobDeliveryManner;
    input: JobDeliveryMannerInput;
  };
  job_invoice: {
    select: JobInvoice;
    input: JobInvoiceInput;
  };
  job_invoice_line: {
    select: JobInvoiceLine;
    input: JobInvoiceLineInput;
  };
  job_part_used: {
    select: JobPartUsed;
    input: JobPartUsedInput;
  };
  job_payment: {
    select: JobPayment;
    input: JobPaymentInput;
  };
  job_receive_condition: {
    select: JobReceiveCondition;
    input: JobReceiveConditionInput;
  };
  job_receive_manner: {
    select: JobReceiveManner;
    input: JobReceiveMannerInput;
  };
  job_status: {
    select: JobStatus;
    input: JobStatusInput;
  };
  job_transaction: {
    select: JobTransaction;
    input: JobTransactionInput;
  };
  job_type: {
    select: JobType;
    input: JobTypeInput;
  };
  product: {
    select: Product;
    input: ProductInput;
  };
  product_brand_model: {
    select: ProductBrandModel;
    input: ProductBrandModelInput;
  };
  purchase_invoice: {
    select: PurchaseInvoice;
    input: PurchaseInvoiceInput;
  };
  purchase_invoice_line: {
    select: PurchaseInvoiceLine;
    input: PurchaseInvoiceLineInput;
  };
  sales_invoice: {
    select: SalesInvoice;
    input: SalesInvoiceInput;
  };
  sales_invoice_line: {
    select: SalesInvoiceLine;
    input: SalesInvoiceLineInput;
  };
  spare_part_master: {
    select: SparePartMaster;
    input: SparePartMasterInput;
  };
  state: {
    select: State;
    input: StateInput;
  };
  stock_adjustment: {
    select: StockAdjustment;
    input: StockAdjustmentInput;
  };
  stock_adjustment_line: {
    select: StockAdjustmentLine;
    input: StockAdjustmentLineInput;
  };
  stock_transaction: {
    select: StockTransaction;
    input: StockTransactionInput;
  };
  stock_transaction_type: {
    select: StockTransactionType;
    input: StockTransactionTypeInput;
  };
  supplier: {
    select: Supplier;
    input: SupplierInput;
  };
  technician: {
    select: Technician;
    input: TechnicianInput;
  };
}

export const tables = {
  app_setting,
  branch,
  brand,
  company_info,
  customer_contact,
  customer_type,
  document_sequence,
  document_type,
  financial_year,
  job,
  job_additional_charge,
  job_delivery_manner,
  job_invoice,
  job_invoice_line,
  job_part_used,
  job_payment,
  job_receive_condition,
  job_receive_manner,
  job_status,
  job_transaction,
  job_type,
  product,
  product_brand_model,
  purchase_invoice,
  purchase_invoice_line,
  sales_invoice,
  sales_invoice_line,
  spare_part_master,
  state,
  stock_adjustment,
  stock_adjustment_line,
  stock_transaction,
  stock_transaction_type,
  supplier,
  technician,
}
