/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@node150483-trace-link.cloudjiffy.net:11085/service_plus_client -t client -s public
 *
 */


export type Json = unknown;

// Table client
export interface Client {
  id: number;
  code: string;
  name: string;
  is_active: boolean;
  gstin: string | null;
  pan: string | null;
  phone: string | null;
  email: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  pincode: string | null;
  country_code: string | null;
  created_at: Date;
  updated_at: Date;
  db_name: string | null;
}
export interface ClientInput {
  id: number;
  code: string;
  name: string;
  is_active?: boolean;
  gstin?: string | null;
  pan?: string | null;
  phone?: string | null;
  email?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  country_code?: string | null;
  created_at?: Date;
  updated_at?: Date;
  db_name?: string | null;
}
const client = {
  tableName: 'client',
  columns: ['id', 'code', 'name', 'is_active', 'gstin', 'pan', 'phone', 'email', 'address_line1', 'address_line2', 'city', 'state', 'pincode', 'country_code', 'created_at', 'updated_at', 'db_name'],
  requiredForInsert: ['id', 'code', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Client,
  $input: null as unknown as ClientInput
} as const;


export interface TableTypes {
  client: {
    select: Client;
    input: ClientInput;
  };
}

export const tables = {
  client,
}
